In [1]:
import sqlite3
from pathlib import Path

import pandas as pd
import csv

In [2]:
df = pd.read_csv('../data/hospital.csv')
df.head(5)

,Unnamed: 0,사업장명,도로명주소,좌표정보(X),좌표정보(Y),지번주소
0,0,광화문동물병원,"서울특별시 종로구 자하문로 35-3, 씨에스코즈빌 101호 (통인동)",197383.197505,452972.118568,서울특별시 종로구 통인동 147-7 씨에스코즈빌
1,1,경희궁 바른 동물병원,"서울특별시 종로구 송월길 99, 상가동 2층 2229호 (홍파동, 경희궁자이 2단지)",196711.256847,452060.860509,서울특별시 종로구 홍파동 42-13 경희궁자이 2단지 상가동 2229호
2,2,선동물병원,"서울특별시 종로구 자하문로 95, 신교빌딩 1층 (신교동)",197278.891939,453572.355621,서울특별시 종로구 신교동 70-10
3,3,폴라동물병원,"서울특별시 종로구 낙산길 311, 지1층 (숭인동)",201451.464239,453137.690825,서울특별시 종로구 숭인동 20-138 지1층
4,4,뉴욕동물병원,"서울특별시 종로구 창경궁로35길 19, 2층 (혜화동)",200079.663985,453836.098563,서울특별시 종로구 혜화동 53-11 2층

In [3]:
df.rename(columns = {'Unnamed: 0' : 'ids'}, inplace = True)
df.head(5)

,ids,사업장명,도로명주소,좌표정보(X),좌표정보(Y),지번주소
0,0,광화문동물병원,"서울특별시 종로구 자하문로 35-3, 씨에스코즈빌 101호 (통인동)",197383.197505,452972.118568,서울특별시 종로구 통인동 147-7 씨에스코즈빌
1,1,경희궁 바른 동물병원,"서울특별시 종로구 송월길 99, 상가동 2층 2229호 (홍파동, 경희궁자이 2단지)",196711.256847,452060.860509,서울특별시 종로구 홍파동 42-13 경희궁자이 2단지 상가동 2229호
2,2,선동물병원,"서울특별시 종로구 자하문로 95, 신교빌딩 1층 (신교동)",197278.891939,453572.355621,서울특별시 종로구 신교동 70-10
3,3,폴라동물병원,"서울특별시 종로구 낙산길 311, 지1층 (숭인동)",201451.464239,453137.690825,서울특별시 종로구 숭인동 20-138 지1층
4,4,뉴욕동물병원,"서울특별시 종로구 창경궁로35길 19, 2층 (혜화동)",200079.663985,453836.098563,서울특별시 종로구 혜화동 53-11 2층

In [2]:
con = sqlite3.connect('../data/hospital.db')
cursor = con.cursor()

In [6]:
cursor.execute("DROP TABLE hospital")

In [7]:
cursor.execute('''
                CREATE TABLE IF NOT EXISTS hospital(
                ids int,
                name text, 
                new_address text,
                x_coor float,
                y_coor float,
                old_address text
                )''')

In [8]:
with open('../data/hospital.csv', 'r', encoding='utf-8') as file:
    csv_data = csv.reader(file)
    next(csv_data) # 첫번째 행은 헤더이므로 건너뜀
    for row in csv_data:
        cursor.execute('INSERT INTO hospital VALUES (?, ?, ?, ?, ?, ?)', row)
con.commit()
con.close()

In [13]:
con = sqlite3.connect('../data/hospital.db')
cursor = con.cursor()

In [14]:
cursor.execute("SELECT * FROM hospital")
rows = cursor.fetchall()

for row in rows:
    print(row)

(0, '광화문동물병원', '서울특별시 종로구 자하문로 35-3, 씨에스코즈빌 101호 (통인동)', 197383.197504794, 452972.118568389, '서울특별시 종로구 통인동 147-7 씨에스코즈빌 ')
(1, '경희궁 바른 동물병원', '서울특별시 종로구 송월길 99, 상가동 2층 2229호 (홍파동, 경희궁자이 2단지)', 196711.256846666, 452060.860508565, '서울특별시 종로구 홍파동 42-13 경희궁자이 2단지 상가동 2229호')
(2, '선동물병원', '서울특별시 종로구 자하문로 95, 신교빌딩 1층 (신교동)', 197278.891939281, 453572.355620921, '서울특별시 종로구 신교동 70-10 ')
(3, '폴라동물병원', '서울특별시 종로구 낙산길 311, 지1층 (숭인동)', 201451.464239337, 453137.690825347, '서울특별시 종로구 숭인동 20-138 지1층 ')
(4, '뉴욕동물병원', '서울특별시 종로구 창경궁로35길 19, 2층 (혜화동)', 200079.663985257, 453836.098562833, '서울특별시 종로구 혜화동 53-11 2층 ')
(5, '해동물병원', '서울특별시 종로구 지봉로 53-1 (창신동)', 201300.617267399, 452512.234050389, '서울특별시 종로구 창신동 80-1 ')
(6, '북악동물병원', '서울특별시 종로구 자하문로 293 (홍지동)', 196420.140799836, 455175.041431888, '서울특별시 종로구 홍지동 127-7 5통5반 지층 3호')
(7, '올리브동물병원', '서울특별시 종로구 자하문로 305 (홍지동)', 196308.215602977, 455218.757468473, '서울특별시 종로구 홍지동 126-8 ')
(8, '우리동물병원', '서울특별시 종로구 지봉로 96-3 (숭인동)', 201312.324500599, 452934.470658927, '서울특별시 종로구 숭인동 52-8 ')
(9, '누리봄동물병원', '서울특별시 종로구 사직로12길 2 (내자동)', 197374.347630839, 452611.452584222, '서울특별시 종로구 내자동 125-3 ')
(10, '대학로동물병원', '서울특별시 종로구 창경궁로 261 (명륜2가)', 199947.178659037, 453593.826987348, '서울특별시 종로구 명륜2가 5-99 1통3반 방산빌라 402호')
(11, '월드펫동물병원', '서울특별시 종로구 평창문화로 75, 글로리아타운 111호 (평창동)', 197212.364862058, 456055.205802855, '서울특별시 종로구 평창동 158-1 글로리아타운 ')
(12, '윤신근박사동물병원', '서울특별시 중구 퇴계로 226 (필동2가)', 199652.596554208, 451038.891443622, '서울특별시 중구 필동2가 53 ')
(13, '황동물병원', '서울특별시 중구 퇴계로 254-1 (묵정동)', 199930.85829926, 451121.344849729, '서울특별시 중구 묵정동 32-1 ')
(14, '대한동물병원', '서울특별시 중구 퇴계로 227 (충무로4가)', 199655.746062675, 451086.874410496, '서울특별시 중구 충무로4가 93-1 ')
(15, '남산동물병원', '서울특별시 중구 다산로 32, 5상가동 217호 (신당동, 남산타운)', 200750.455125653, 449638.824308081, '서울특별시 중구 신당동 844 남산타운 ')
(16, '미래지동물의료센터', '서울특별시 중구 다산로 107, 2층 (신당동)', 200783.119589726, 450153.784342829, '서울특별시 중구 신당동 368-19 ')
(17, '백슬동물병원', '서울특별시 중구 만리재로 175, 지하1층 401-1호 (만리동2가, 서울역센트럴자이)', 196697.116895888, 450217.095147509, '서울특별시 중구 만리동2가 273 서울역센트럴자이 ')
(18, '신당 좋아요 동물병원', '서울특별시 중구 다산로36길 83, 1층 (신당동)', 201618.834979518, 450916.705246197, '서울특별시 중구 신당동 44-17 ')
(19, '바른동물병원', '서울특별시 중구 퇴계로 447, 1층 131호 (황학동, 황학 아크로타워)', 201866.039519433, 451543.337800303, '서울특별시 중구 황학동 2523 황학 아크로타워 ')
(20, '애니컴 메디컬센터', '서울특별시 중구 다산로 83-1, 3층 (신당동)', 200640.466334248, 449978.493556843, '서울특별시 중구 신당동 353-130 ')
(21, '메종동물병원', '서울특별시 중구 다산로 230, 하나빌딩 1층 (신당동)', 201341.792321443, 451246.571908878, '서울특별시 중구 신당동 102-6 ')
(22, '웰니스클리닉(청계천점)', '서울특별시 중구 청계천로 400, 지하 1층 (황학동, 롯데캐슬베네치아)', 201823.908977364, 452076.818664092, '서울특별시 중구 황학동 2545 롯데캐슬베네치아 ')
(23, '헬릭스동물심장수술센터', '서울특별시 중구 을지로38길 20, 뉴천지관광호텔 2층 (을지로5가)', 200225.983119633, 451511.262755282, '서울특별시 중구 을지로5가 133-1 뉴천지관광호텔 ')
(24, '헬릭스동물암센터', '서울특별시 중구 을지로38길 20, 뉴천지관광호텔 1층 (을지로5가)', 200225.983119633, 451511.262755282, '서울특별시 중구 을지로5가 133-1 뉴천지관광호텔 ')
(25, '서울동물영상종양센터', '서울특별시 중구 을지로38길 20, 뉴천지관광호텔 1층 (을지로5가)', 200225.983119633, 451511.262755282, '서울특별시 중구 을지로5가 133-1 뉴천지관광호텔 ')
(26, '웰튼동물의료센터', '서울특별시 중구 난계로 197, 1,2,4층 (황학동)', 201985.829607973, 451869.587314453, '서울특별시 중구 황학동 1596 ')
(27, '에스디(SD)동물영상센터,서울', '서울특별시 중구 왕십리로 407, B1-1호 (신당동, 신당 파인힐 하나유보라)', 202131.747052459, 451330.482879118, '서울특별시 중구 신당동 855 신당 파인힐 하나유보라 ')
(28, '에스디(SD)동물의료센터,서울', '서울특별시 중구 왕십리로 407, 신당 파인힐 하나유보라 B1층 03,04,05호 (신당동, 신당 파인힐 하나유보라)', 202131.747052459, 451330.482879118, '서울특별시 중구 신당동 855 신당 파인힐 하나유보라 ')
(29, '힐스타운 동물병원', '서울특별시 중구 다산로 32, 스포츠상가동 106-2호 (신당동, 남산타운)', 200750.455125653, 449638.824308081, '서울특별시 중구 신당동 844 남산타운 ')
(30, '바우미우동물병원', '서울특별시 중구 다산로 175, 명덕빌딩 (신당동)', 201064.963697104, 450779.720971036, '서울특별시 중구 신당동 336-3 명덕빌딩 ')
(31, '더베이스 동물피부과병원', '서울특별시 용산구 한강대로 95, B동 지하2층 263호 (한강로2가, 래미안용산 더 센트럴)', 197011.737528847, 447430.100250997, '서울특별시 용산구 한강로2가 422 래미안용산 더 센트럴 ')
(32, '청화종합동물병원', '서울특별시 용산구 장문로 18, 2층 (동빙고동)', 199254.608612617, 447354.661580526, '서울특별시 용산구 동빙고동 7-19 ')
(33, '펫토이동물병원', '서울특별시 용산구 대사관로 32 (한남동)', 200079.108817319, 447917.947059496, '서울특별시 용산구 한남동 653-26 ')
(34, '금강동물병원', '서울특별시 용산구 이촌로 300, 렉스상가 8-1,8-2호 (이촌동)', 198165.767858385, 446185.244544796, '서울특별시 용산구 이촌동 301-263 렉스상가 8-1,8-2호 ')
(35, '라온동물병원', '서울특별시 용산구 회나무로 7, 2층 (이태원동)', 198842.61612083, 448493.993525383, '서울특별시 용산구 이태원동 647 ')
(36, '아프리카동물병원', '서울특별시 용산구 후암로 32 (후암동)', 197980.868340519, 449605.434772664, '서울특별시 용산구 후암동 244-11 ')
(37, '엉클장동물병원', '서울특별시 용산구 백범로 341, A동 지상1층 106호 (원효로1가, 리첸시아 용산)', 197045.849468346, 448447.558967085, '서울특별시 용산구 원효로1가 133-3 리첸시아 용산 A동 106호')
(38, '펫동물병원', '서울특별시 용산구 백범로 285, 지상1층 (효창동)', 196490.844311727, 448594.448927151, '서울특별시 용산구 효창동 79-1 지상1층 ')
(39, '달래동물의료센터', '서울특별시 용산구 한남대로 76, 한남프라자 2층 (한남동)', 200506.187313451, 448146.173245501, '서울특별시 용산구 한남동 707-36 한남프라자 2층 ')
(40, '민트동물병원', '서울특별시 용산구 원효로 51, 119호 (산천동, 삼성테마트)', 195547.140326252, 447976.775939762, '서울특별시 용산구 산천동 202 삼성테마트 119호 ')
(41, '이태원동물병원', '서울특별시 용산구 녹사평대로 210, 지하1, 1, 2층층 일부호 (이태원동)', 198802.476070336, 448239.820740686, '서울특별시 용산구 이태원동 531 ')
(42, '퍼스동물병원', '서울특별시 용산구 신흥로 54, 106호 (용산동2가, 북동연립)', 198855.032090543, 448982.633361938, '서울특별시 용산구 용산동2가 45-1 106호 ')
(43, '좋아서하는 동물병원', '서울특별시 용산구 백범로 341, B동 지상1층 113,114호 (원효로1가, 리첸시아 용산)', 197045.849468346, 448447.558967085, '서울특별시 용산구 원효로1가 133-3 리첸시아 용산 B동 113,114호 ')
(44, '바다동물병원(Bada Animal Hospital)', '서울특별시 용산구 서빙고로 67, 지하1층 비21호 (용산동5가, 파크타워)', 197338.915067396, 446893.484429691, '서울특별시 용산구 용산동5가 24 파크타워 지하1층 비21호')
(45, '24시 시유동물메디컬센터', '서울특별시 용산구 이촌로64길 24, 지상1층 101호 (이촌동)', 197270.042278677, 446419.923247168, '서울특별시 용산구 이촌동 302-88 지상1층 101호 ')
(46, '베이동물병원', '서울특별시 용산구 이촌로 248, 11동 102호 (이촌동, 한강맨션)', 197722.571038558, 446344.591216568, '서울특별시 용산구 이촌동 300-23 한강맨션 11동 102호')
(47, '더힐동물의료센터', '서울특별시 용산구 독서당로 81-1, 아이리스프라자 지상3층 (한남동)', 200779.182, 448049.195666666, '서울특별시 용산구 한남동 29-6 아이리스프라자 지상3층 ')
(48, '원스동물병원', '서울특별시 용산구 청파로47길 16, 지상1층 (청파동2가)', 197234.131475852, 449191.560826572, '서울특별시 용산구 청파동2가 90-20 지상1층 ')
(49, '이상윤동물병원', '서울특별시 용산구 이촌로 248, 31동 105-2호 (이촌동, 한강맨션)', 197722.571038558, 446344.591216568, '서울특별시 용산구 이촌동 300-23 한강맨션 ')
(50, '에스동물병원', '서울특별시 용산구 서빙고로 17, 헤링턴스퀘어 센트럴파크 몰동 1146, 1147호 (한강로3가)', 197056.728931087, 447077.126289262, '서울특별시 용산구 한강로3가 98 ')
(51, '위런한방재활동물병원', '서울특별시 용산구 한강대로 95, 225호 (한강로2가, 래미안용산 더 센트럴)', 197011.737528847, 447430.100250997, '서울특별시 용산구 한강로2가 422 래미안용산 더 센트럴 225호')
(52, '한남심장내과동물병원', '서울특별시 용산구 독서당로 46, 111호 (한남동, 한남아이파크)', 200571.725921493, 447793.924058853, '서울특별시 용산구 한남동 828 한남아이파크 ')
(53, '용산마음동물병원', '서울특별시 용산구 백범로 340, 2층 (원효로2가)', 196979.093087733, 448380.524209959, '서울특별시 용산구 원효로2가 1-36 ')
(54, '남산동물병원', '서울특별시 용산구 후암로 51, 지상1층 (후암동)', 197907.242547187, 449803.89961095, '서울특별시 용산구 후암동 63-1 지상1층 ')
(55, '효창동물병원', '서울특별시 용산구 백범로 293 (효창동)', 196561.891893717, 448563.455747747, '서울특별시 용산구 효창동 70-11 ')
(56, '열린동물종합병원', '서울특별시 용산구 원효로 171, 신영빌딩 (원효로2가)', 196549.89584221, 448153.524398611, '서울특별시 용산구 원효로2가 84-10 신영빌딩 ')
(57, '원효종합동물병원', '서울특별시 용산구 새창로 122-2(용문동)', 196459.674190442, 448255.165737565, '서울특별시 용산구 용문동 25-36 ')
(58, '한사랑동물병원', '서울특별시 용산구 신흥로 36-1 (용산동2가)', 198816.63972746, 448827.72464503, '서울특별시 용산구 용산동2가 45-7 ')
(59, '중심동물병원', '서울특별시 성동구 마조로 55, 상가동 1층 119호 (마장동, 금호어울림아파트)', 203597.7587591, 451160.268443273, '서울특별시 성동구 마장동 821 금호어울림아파트 ')
(60, '평생피부과동물병원', '서울특별시 성동구 행당로 76, 110호 (행당동, 한진노변상가)', 202511.142930696, 450401.303715561, '서울특별시 성동구 행당동 346 한진노변상가 110호')
(61, '오렌지동물병원', '서울특별시 성동구 행당로8길 41-2 (행당동)', 202931.789940848, 450419.387012901, '서울특별시 성동구 행당동 322-100 ')
(62, '한빛동물병원', '서울특별시 성동구 금호산길 58(금호동2가)', 201657.926313791, 450119.508052252, '서울특별시 성동구 금호동2가 485-1 ')
(63, '아지동물병원', '서울특별시 성동구 독서당로 289 (금호동4가,지상1층)', 201790.117515658, 449530.70769686, '서울특별시 성동구 금호동4가 1108 지상1층 ')
(64, '24시센트럴동물메디컬센터', '서울특별시 성동구 고산자로 207 (행당동)', 202907.218919388, 450712.086716399, '서울특별시 성동구 행당동 318-36 ')
(65, '이윤세동물병원', '서울특별시 성동구 행당로 76, 한진노변상가 1,2층 108호109호203호 (행당동)', 202511.142930696, 450401.303715561, '서울특별시 성동구 행당동 346 한진노변상가 109호')
(66, '한양동물메디컬센터', '서울특별시 성동구 왕십리로 282 (행당동)', 203200.771278441, 450821.216569269, '서울특별시 성동구 행당동 226-3 ')
(67, '옥수수 동물병원', '서울특별시 성동구 독서당로40길 39, 어울림상가 301~304호 (옥수동)', 201538.05612719, 448894.755196992, '서울특별시 성동구 옥수동 560 어울림상가 301~4호')
(68, '도담동물병원(출장진료전문 동물병원)', '서울특별시 성동구 독서당로59길 84, 신동아아파트상가동 1층 111호 (행당동)', 202831.905687785, 450233.87834092, '서울특별시 성동구 행당동 344 111호')
(69, '라임동물병원', '서울특별시 성동구 무학로 16 (홍익동)', 202608.881117477, 451473.310104052, '서울특별시 성동구 홍익동 398-2 ')
(70, '바른동물병원', '서울특별시 성동구 독서당로 270, 상가동 2층 206호 (금호동4가, 금호동 대우아파트)', 201669.803556903, 449301.451523245, '서울특별시 성동구 금호동4가 800 금호동대우아파트 상가동 206호')
(71, '기린동물병원', '서울특별시 성동구 마장로 296 (마장동)', 203709.590135792, 451490.666502232, '서울특별시 성동구 마장동 791-9 ')
(72, '왕십리조은동물병원', '서울특별시 성동구 왕십리로 381 (하왕십리동)', 202393.457305335, 451365.326207693, '서울특별시 성동구 하왕십리동 892-4 ')
(73, '오석헌동물병원', '서울특별시 성동구 매봉길 13, 1층 420호 (옥수동, 래미안옥수리버젠상가)', 201153.981577199, 449188.97052419, '서울특별시 성동구 옥수동 561 래미안옥수리버젠 상가동 420호')
(74, '제인동물병원', '서울특별시 성동구 뚝섬로 395 (성수동2가)', 204763.80767636, 448534.113764965, '서울특별시 성동구 성수동2가 339-23 ')
(75, '금호동물병원', '서울특별시 성동구 금호로 105, 비201호 (금호동2가, 래미안하이리버 상가동)', 202098.97937718, 449891.972244601, '서울특별시 성동구 금호동2가 1217 래미안하이리버 상가동 비201호')
(76, '포레동물병원', '서울특별시 성동구 상원길 59, 쌍용아파트상가B동 107호 (성수동1가)', 204093.39625466, 449695.084129637, '서울특별시 성동구 성수동1가 706 쌍용아파트상가B동 107호')
(77, '스테이동물병원', '서울특별시 성동구 매봉길 50 (옥수동, 이편한세상옥수파크힐스)', 201157.877298502, 449563.280012747, '서울특별시 성동구 옥수동 528 이편한세상옥수파크힐스 ')
(78, '바라봄동물병원', '서울특별시 성동구 왕십리로 410, 127동 지하층 030호 (하왕십리동, 센트라스)', 202372.912023599, 451536.680876573, '')
(79, '달링동물병원', '서울특별시 성동구 왕십리로 16 (성수동1가, 트리마제)', 203911.513091074, 448508.756036449, '서울특별시 성동구 성수동1가 718 트리마제 ')
(80, '베이지동물병원', '서울특별시 성동구 왕십리로 410, D동 106호 (하왕십리동, 센트라스)', 202372.912023599, 451536.680876573, '서울특별시 성동구 하왕십리동 1070 센트라스상가 D동 106호')
(81, '오늘동물병원', '서울특별시 성동구 왕십리로 104, 영화빌딩 2층 (성수동1가)', 203895.448794593, 449401.289888823, '서울특별시 성동구 성수동1가 656-968 영화빌딩 2층 ')
(82, '조형선외과동물병원', '서울특별시 성동구 금호로 146, 제1, 2층 (금호동1가)', 201774.580419376, 450208.959848768, '서울특별시 성동구 금호동1가 526 ')
(83, 'BK심장동물병원', '서울특별시 성동구 고산자로6길 40, 행당동 레몬프라자 1층 113호 (행당동)', 203071.959180897, 450665.532604254, '서울특별시 성동구 행당동 140 행당동 레몬프라자 1층 113호')
(84, '성수 숲속 피부과 동물병원', '서울특별시 성동구 서울숲2길 32-14, 지하1층 B114호 (성수동1가, 갤러리아 포레)', 203684.281166499, 449280.97521227, '서울특별시 성동구 성수동1가 685-696 갤러리아 포레 지하1층 B114호')
(85, '왕십리동물병원', '서울특별시 성동구 무학로6길 50, 101동 225호 (도선동, 성동삼성쉐르빌)', 203017.021457357, 451346.281102634, '서울특별시 성동구 도선동 69 성동삼성쉐르빌 101동 225호')
(86, '보람동물병원', '서울특별시 광진구 군자로 84 (군자동)', 206218.599101694, 449808.490100535, '서울특별시 광진구 군자동 363-4 ')
(87, '애플동물병원', '서울특별시 광진구 천호대로 642-1 (능동)', 207733.266195381, 450105.913833549, '서울특별시 광진구 능동 256-1 ')
(88, '로엘동물병원', '서울특별시 광진구 뚝섬로 622-1 (자양동)', 206893.84345075, 447758.903010754, '서울특별시 광진구 자양동 606-14 ')
(89, '해맑은동물병원', '서울특별시 광진구 뚝섬로 670 (자양동)', 207349.510653919, 447708.939689927, '서울특별시 광진구 자양동 662-13 ')
(90, '노룬산동물병원', '서울특별시 광진구 뚝섬로 462 (자양동)', 205390.463339147, 448294.665199062, '서울특별시 광진구 자양동 236-127 ')
(91, '준동물병원', '서울특별시 광진구 뚝섬로 541 (자양동)', 206150.655471501, 448076.720689255, '서울특별시 광진구 자양동 553-588 ')
(92, '서울어린이대공원동물병원', '서울특별시 광진구 능동로 216 (능동)', 207139.204095368, 449705.67643744, '서울특별시 광진구 능동 18-0 ')
(93, '나루동물병원', '서울특별시 광진구 아차산로 537-17 (광장동)', 208729.170395929, 448995.808404463, '서울특별시 광진구 광장동 582 ')
(94, '다온동물병원', '서울특별시 광진구 면목로 142 (중곡동)', 207128.898416579, 451521.824189635, '서울특별시 광진구 중곡동 193-29 ')
(95, '자양동물병원', '서울특별시 광진구 뚝섬로52길 4 (자양동)', 206943.894875237, 447730.416384887, '서울특별시 광진구 자양동 606-27 ')
(96, '드림펫 동물병원', '서울특별시 광진구 능동로 407, 2층 (중곡동)', 207333.639771374, 451464.267096677, '서울특별시 광진구 중곡동 166-6 ')
(97, '서울동물병원', '서울특별시 광진구 천호대로 623-1, 1층 (중곡동)', 207624.556805359, 450257.044484869, '서울특별시 광진구 중곡동 119-7 ')
(98, '로얄 도그앤캣 메디컬센터', '서울특별시 광진구 능동로 49 (자양동, 영지빌딩)', 205969.966011569, 448175.917404606, '서울특별시 광진구 자양동 550-1 ')
(99, '파라곤동물병원', '서울특별시 광진구 광나루로 361, 2동 103호 (군자동, 광진동양파라곤)', 206091.938587177, 449581.249922815, '')
(100, '쿨펫동물병원', '서울특별시 광진구 아차산로 272 (자양동, 이마트 자양점)', 206349.675048285, 448396.939704285, '')
(101, '연두동물병원', '서울특별시 광진구 광나루로 524 (구의동)', 207679.128954008, 449166.073716992, '')
(102, '광진24시필동물병원', '서울특별시 광진구 광나루로56길 66, 201, 202호 (구의동)', 208403.746065593, 448490.239179557, '서울특별시 광진구 구의동 611 구의현대2단지아파트 ')
(103, '스마트동물병원군자점', '서울특별시 광진구 능동로43길 3-5 (중곡동)', 207107.928644491, 450953.281007512, '서울특별시 광진구 중곡동 162-8 ')
(104, '아이본 동물병원', '서울특별시 광진구 자양로 65, 화성빌딩 1층 (자양동)', 207386.983040962, 447934.708019366, '서울특별시 광진구 자양동 657-5 화성빌딩 1층 ')
(105, '우주동물병원', '서울특별시 광진구 자양로15길 30, 1층 (자양동)', 207169.000147705, 448162.523899287, '서울특별시 광진구 자양동 612-56 ')
(106, '다봄 동물병원', '서울특별시 광진구 자양로 163, 우남빌딩 (구의동)', 207334.35237407, 448890.470998334, '서울특별시 광진구 구의동 254-36 우남빌딩 1층 ')
(107, '아크로벳 내과동물병원', '서울특별시 광진구 광나루로 582, 세종빌딩 1층 (구의동)', 208181.517388785, 448984.848324887, '서울특별시 광진구 구의동 202-3 1층 ')
(108, '비비동물병원', '서울특별시 광진구 능동로 21, 1층 (자양동)', 205877.28221374, 447919.248318372, '서울특별시 광진구 자양동 65-1 ')
(109, '서울대학교동물검진센터', '서울특별시 광진구 구의강변로 46, 금성빌딩 1,2층 (구의동)', 208073.305054801, 448077.378533521, '서울특별시 광진구 구의동 594-4 금성빌딩 ')
(110, 'Severance AMC', '서울특별시 광진구 천호대로 512, 군자빌딩 b층 02호 (군자동)', 206582.005887061, 450685.591302855, '서울특별시 광진구 군자동 466-17 군자빌딩 ')
(111, '프라임동물병원', '서울특별시 광진구 아차산로 451 (구의동)', 208060.467769154, 448564.992528913, '서울특별시 광진구 구의동 659 세림리오빌아파트 제비1-1호')
(112, '동서울동물병원', '서울특별시 광진구 아차산로 493 (광장동)', 208431.92764385, 448842.232617503, '서울특별시 광진구 광장동 517-5 삼익아파트 ')
(113, '피카소동물병원', '서울특별시 광진구 광나루로 392-1 (화양동)', 206405.844680642, 449450.171000912, '서울특별시 광진구 화양동 216 ')
(114, '용마동물병원', '서울특별시 광진구 용마산로 66 (중곡동)', 207695.480720925, 450809.028344187, '서울특별시 광진구 중곡동 58-18 ')
(115, '중곡동물병원', '서울특별시 광진구 긴고랑로 47 (중곡동)', 207137.468593835, 451166.351150671, '서울특별시 광진구 중곡동 241-34 ')
(116, '방주종합동물병원', '서울특별시 광진구 능동로 334 (중곡동)', 207082.19653446, 450786.420735596, '서울특별시 광진구 중곡동 161-27 ')
(117, '광진동물의료센터', '서울특별시 광진구 광나루로 507 (구의동)', 207526.590151138, 449223.749584778, '서울특별시 광진구 구의동 68-37 ')
(118, '건국대학교 부속 동물병원', '서울특별시 광진구 능동로 120 (화양동)', 206445.881091692, 448922.881688102, '서울특별시 광진구 화양동 1 ')
(119, '쥬라기동물병원', '서울특별시 광진구 광나루로 601 (광장동)', 208344.912915338, 448875.286459939, '서울특별시 광진구 광장동 530-39 ')
(120, '이다종합동물병원', '서울특별시 광진구 뚝섬로 504 (자양동)', 205770.381275106, 448175.187322101, '서울특별시 광진구 자양동 553-280 ')
(121, '나래동물병원', '서울특별시 광진구 능동로 283 (군자동)', 206836.098040667, 450344.799584363, '서울특별시 광진구 군자동 1-2 ')
(122, '청량리 슬기 동물병원', '서울특별시 동대문구 왕산로 186, 청량리역 우남SL타워300 218, 219호 (전농동)', 203816.673034515, 453023.128996239, '서울특별시 동대문구 전농동 620-15 청량리역 우남SL타워300 ')
(123, '이즈 동물병원', '서울특별시 동대문구 이문로35길 12, 상가 C동 102호 (이문동, 래미안라그란데아파트)', 205249.265435832, 455308.651763587, '서울특별시 동대문구 이문동 257-42 래미안라그란데아파트 ')
(124, '아이랑 동물병원', '서울특별시 동대문구 이문로35길 12, 상가 A동 101호 (이문동, 래미안라그란데아파트)', 205249.265435832, 455308.651763587, '서울특별시 동대문구 이문동 257-42 래미안라그란데아파트 ')
(125, '심재웅동물병원', '서울특별시 동대문구 망우로 120 (휘경동)', 205804.989007148, 454312.287025523, '서울특별시 동대문구 휘경동 34-48 ')
(126, '박철환동물병원', '서울특별시 동대문구 사가정로 221 (장안동)', 206086.591362203, 452959.773010702, '서울특별시 동대문구 장안동 100-8 ')
(127, '뉴월드동물병원', '서울특별시 동대문구 한천로 94, 1층 (장안동)', 205631.56459772, 451925.907664051, '서울특별시 동대문구 장안동 186-12 ')
(128, '그랜드동물병원', '서울특별시 동대문구 전농로 77(답십리동)', 204974.829709532, 452169.781296696, '서울특별시 동대문구 답십리동 250-1 ')
(129, '애니케어동물병원', '서울특별시 동대문구 이문로 80 (이문동)', 205129.365335764, 454637.821983342, '서울특별시 동대문구 이문동 324-3 ')
(130, '푸른종합동물병원', '서울특별시 동대문구 홍릉로 48-1, 1층 (청량리동)', 203823.018467941, 453587.707759897, '서울특별시 동대문구 청량리동 359 ')
(131, '장평25시동물종합병원', '서울특별시 동대문구 장한로 139 (장안동)', 206237.158132452, 452292.449080256, '서울특별시 동대문구 장안동 307-3 ')
(132, '안암동물병원', '서울특별시 동대문구 안암로 40, 1층 (용두동)', 202296.946950935, 453139.055096553, '서울특별시 동대문구 용두동 732-5 ')
(133, '주주동물병원', '서울특별시 동대문구 사가정로 121 (전농동)', 205096.03189952, 452842.927086522, '서울특별시 동대문구 전농동 38-24 ')
(134, '맑은 동물병원', '서울특별시 동대문구 청계천로 417, 108호 (신설동, 청계천 대성 스카이렉스1)', 202042.817335648, 452190.100421552, '서울특별시 동대문구 신설동 109-13 청계천 대성 스카이렉스1 ')
(135, '그린동물병원', '서울특별시 동대문구 정릉천동로 58, 1층 125호 (용두동, 롯데캐슬피렌체)', 203085.866786086, 452766.014195644, '서울특별시 동대문구 용두동 790 롯데캐슬피렌체 ')
(136, '엘동물병원', '서울특별시 동대문구 고산자로 393-5 (용두동)', 203254.520083136, 452487.042671279, '서울특별시 동대문구 용두동 38-17 ')
(137, '제연동물병원', '서울특별시 동대문구 답십리로 77 (전농동)', 204313.869527831, 452538.14193671, '서울특별시 동대문구 전농동 652-1 ')
(138, 'VIP동물의료센터 동대문점', '서울특별시 동대문구 한천로14길 87(장안동)', 205899.907023899, 451571.351779533, '서울특별시 동대문구 장안동 376-3 ')
(139, '페트로동물의료원', '서울특별시 동대문구 답십리로63길 1(장안동)', 205911.321964079, 452287.844106267, '서울특별시 동대문구 장안동 140-8 ')
(140, '하나동물병원', '서울특별시 동대문구 망우로 66 (휘경동)', 205314.479215834, 454133.191843723, '서울특별시 동대문구 휘경동 267-84 ')
(141, '봄봄동물병원', '서울특별시 동대문구 회기로18길 46 (회기동)', 204704.034122842, 454227.304386333, '서울특별시 동대문구 회기동 62-8 ')
(142, '아띠동물의료센터', '서울특별시 동대문구 사가정로 51 (전농동)', 204553.458408807, 452384.461701131, '서울특별시 동대문구 전농동 322-31 ')
(143, '스마트동물병원', '서울특별시 동대문구 한천로 164, 1층 (장안동)', 205908.898385821, 452581.997774717, '서울특별시 동대문구 장안동 483 ')
(144, '바론동물병원', '서울특별시 동대문구 이문로 136, 2층 208호 (이문동, 이문동 웰츠타워)', 205396.363734301, 455131.683241064, '서울특별시 동대문구 이문동 292-10 이문동 웰츠타워 ')
(145, '더케이동물병원', '서울특별시 동대문구 답십리로 140, 세기프라자 2층 211호 (답십리동)', 204845.874285687, 452243.87695363, '서울특별시 동대문구 답십리동 1003-2 세기프라자 ')
(146, '현대종합동물병원', '서울특별시 동대문구 답십리로 293, 1층 (장안동)', 206384.176300093, 452248.684634996, '서울특별시 동대문구 장안동 330-2 ')
(147, '하이유 동물병원', '서울특별시 동대문구 전농로 15-3 (답십리동)', 204869.688144425, 451594.33252299, '서울특별시 동대문구 답십리동 490-57 ')
(148, '아인스동물병원', '서울특별시 동대문구 장한로 44, 1층 (장안동)', 205883.994796584, 451422.978298566, '서울특별시 동대문구 장안동 435-6 ')
(149, '아이원 동물병원', '서울특별시 동대문구 전농로 80, 1층 (답십리동)', 205018.210432587, 452185.824073309, '서울특별시 동대문구 답십리동 52-3 ')
(150, '땅콩동물병원', '서울특별시 동대문구 답십리로 224-1 (답십리동)', 205696.046346636, 452256.64849964, '서울특별시 동대문구 답십리동 3-125 ')
(151, '24시 동대문 루시드 동물메디컬센터', '서울특별시 동대문구 전농로 57-1, 1층,2층,지하1층 동대문 루시드 동물메디컬센터 (답십리동)', 204958.890769622, 451983.572742918, '서울특별시 동대문구 답십리동 259-22 ')
(152, '서울동물복지지원센터 동대문 동물병원', '서울특별시 동대문구 무학로 201 (용두동)', 202523.469147286, 453317.110098416, '서울특별시 동대문구 용두동 726-1 ')
(153, '진서동물병원', '서울특별시 중랑구 신내로10길 7 (신내동)', 208400.763171651, 455823.471989854, '서울특별시 중랑구 신내동 571-8 ')
(154, '세진동물병원', '서울특별시 중랑구 망우로 415(망우동)', 208613.331372822, 455266.331938295, '서울특별시 중랑구 망우동 488-14 ')
(155, '숲속동물병원', '서울특별시 중랑구 겸재로 207, 1층 (면목동)', 207928.911342193, 454115.499601712, '서울특별시 중랑구 면목동 103-4 1층 ')
(156, '면목동물병원', '서울특별시 중랑구 사가정로 363 (면목동)', 207429.833336087, 453216.12116107, '서울특별시 중랑구 면목동 606-6 ')
(157, '하니동물병원', '서울특별시 중랑구 신내로 225, 디아뜨갤러리 142호 (신내동)', 207990.479257211, 457183.637796144, '서울특별시 중랑구 신내동 648 디아뜨갤러리 ')
(158, '한국동물메디컬센터(KAMC)', '서울특별시 중랑구 겸재로 165, 1,2층 (면목동)', 207517.256308479, 453990.823070309, '서울특별시 중랑구 면목동 119-10 1,2층 ')
(159, '닥터 아이펫 동물병원', '서울특별시 중랑구 망우로 315, 2층 (상봉동)', 207655.291092379, 454993.657588592, '서울특별시 중랑구 상봉동 99-10 ')
(160, '행복이 있는 동물병원', '서울특별시 중랑구 봉화산로 232, B동 1층 (신내동)', 208614.435553033, 456169.871765864, '서울특별시 중랑구 신내동 405-5 ')
(161, '보담동물병원', '서울특별시 중랑구 용마산로 434 (면목동, 청파빌딩)', 208533.165197782, 454186.696918605, '서울특별시 중랑구 면목동 17-31 ')
(162, '로얄동물암치료센터', '서울특별시 중랑구 동일로 640, 지하 2층 (면목동)', 207017.81527047, 453914.639780644, '서울특별시 중랑구 면목동 146-75 ')
(163, '아이봄 동물병원', '서울특별시 중랑구 신내로 66 (신내동)', 208374.549467469, 455862.278991004, '서울특별시 중랑구 신내동 563-2 ')
(164, '레미 동물병원', '서울특별시 중랑구 동일로 593, 2층 (면목동)', 206949.692364552, 453453.28377601, '서울특별시 중랑구 면목동 172-93 ')
(165, '치료해주오 동물병원 중랑묵동점', '서울특별시 중랑구 동일로 925, 3층 (묵동)', 206712.645739265, 456738.441211434, '서울특별시 중랑구 묵동 238-8 하태윤산부인과 ')
(166, '닥터멍동물병원', '서울특별시 중랑구 상봉로 17, 1층 (면목동)', 208243.910432602, 453913.946459696, '서울특별시 중랑구 면목동 71-41 ')
(167, '로얄동물메디컬센터 본원', '서울특별시 중랑구 동일로 640, 2층, 3층 (면목동)', 207017.81527047, 453914.639780644, '서울특별시 중랑구 면목동 146-75 ')
(168, '로얄동물외과수술센터', '서울특별시 중랑구 동일로 640, 지하1, 지상4층 (면목동)', 207017.81527047, 453914.639780644, '서울특별시 중랑구 면목동 146-75 ')
(169, '혜원동물병원', '서울특별시 중랑구 면목로 341, 1층 (면목동)', 207729.175659582, 453342.232542102, '서울특별시 중랑구 면목동 497-7 ')
(170, '중랑차동물병원', '서울특별시 중랑구 중랑천로 81, 101호 (상봉동)', 206345.47354923, 454460.821850917, '서울특별시 중랑구 상봉동 137-16 ')

In [15]:
cursor.execute("SELECT * FROM hospital WHERE new_address LIKE '서울%'")
rows = cursor.fetchall()

for row in rows:
    print(row)

(0, '광화문동물병원', '서울특별시 종로구 자하문로 35-3, 씨에스코즈빌 101호 (통인동)', 197383.197504794, 452972.118568389, '서울특별시 종로구 통인동 147-7 씨에스코즈빌 ')
(1, '경희궁 바른 동물병원', '서울특별시 종로구 송월길 99, 상가동 2층 2229호 (홍파동, 경희궁자이 2단지)', 196711.256846666, 452060.860508565, '서울특별시 종로구 홍파동 42-13 경희궁자이 2단지 상가동 2229호')
(2, '선동물병원', '서울특별시 종로구 자하문로 95, 신교빌딩 1층 (신교동)', 197278.891939281, 453572.355620921, '서울특별시 종로구 신교동 70-10 ')
(3, '폴라동물병원', '서울특별시 종로구 낙산길 311, 지1층 (숭인동)', 201451.464239337, 453137.690825347, '서울특별시 종로구 숭인동 20-138 지1층 ')
(4, '뉴욕동물병원', '서울특별시 종로구 창경궁로35길 19, 2층 (혜화동)', 200079.663985257, 453836.098562833, '서울특별시 종로구 혜화동 53-11 2층 ')
(5, '해동물병원', '서울특별시 종로구 지봉로 53-1 (창신동)', 201300.617267399, 452512.234050389, '서울특별시 종로구 창신동 80-1 ')
(6, '북악동물병원', '서울특별시 종로구 자하문로 293 (홍지동)', 196420.140799836, 455175.041431888, '서울특별시 종로구 홍지동 127-7 5통5반 지층 3호')
(7, '올리브동물병원', '서울특별시 종로구 자하문로 305 (홍지동)', 196308.215602977, 455218.757468473, '서울특별시 종로구 홍지동 126-8 ')
(8, '우리동물병원', '서울특별시 종로구 지봉로 96-3 (숭인동)', 201312.324500599, 452934.470658927, '서울특별시 종로구 숭인동 52-8 ')
(9, '누리봄동물병원', '서울특별시 종로구 사직로12길 2 (내자동)', 197374.347630839, 452611.452584222, '서울특별시 종로구 내자동 125-3 ')
(10, '대학로동물병원', '서울특별시 종로구 창경궁로 261 (명륜2가)', 199947.178659037, 453593.826987348, '서울특별시 종로구 명륜2가 5-99 1통3반 방산빌라 402호')
(11, '월드펫동물병원', '서울특별시 종로구 평창문화로 75, 글로리아타운 111호 (평창동)', 197212.364862058, 456055.205802855, '서울특별시 종로구 평창동 158-1 글로리아타운 ')
(12, '윤신근박사동물병원', '서울특별시 중구 퇴계로 226 (필동2가)', 199652.596554208, 451038.891443622, '서울특별시 중구 필동2가 53 ')
(13, '황동물병원', '서울특별시 중구 퇴계로 254-1 (묵정동)', 199930.85829926, 451121.344849729, '서울특별시 중구 묵정동 32-1 ')
(14, '대한동물병원', '서울특별시 중구 퇴계로 227 (충무로4가)', 199655.746062675, 451086.874410496, '서울특별시 중구 충무로4가 93-1 ')
(15, '남산동물병원', '서울특별시 중구 다산로 32, 5상가동 217호 (신당동, 남산타운)', 200750.455125653, 449638.824308081, '서울특별시 중구 신당동 844 남산타운 ')
(16, '미래지동물의료센터', '서울특별시 중구 다산로 107, 2층 (신당동)', 200783.119589726, 450153.784342829, '서울특별시 중구 신당동 368-19 ')
(17, '백슬동물병원', '서울특별시 중구 만리재로 175, 지하1층 401-1호 (만리동2가, 서울역센트럴자이)', 196697.116895888, 450217.095147509, '서울특별시 중구 만리동2가 273 서울역센트럴자이 ')
(18, '신당 좋아요 동물병원', '서울특별시 중구 다산로36길 83, 1층 (신당동)', 201618.834979518, 450916.705246197, '서울특별시 중구 신당동 44-17 ')
(19, '바른동물병원', '서울특별시 중구 퇴계로 447, 1층 131호 (황학동, 황학 아크로타워)', 201866.039519433, 451543.337800303, '서울특별시 중구 황학동 2523 황학 아크로타워 ')
(20, '애니컴 메디컬센터', '서울특별시 중구 다산로 83-1, 3층 (신당동)', 200640.466334248, 449978.493556843, '서울특별시 중구 신당동 353-130 ')
(21, '메종동물병원', '서울특별시 중구 다산로 230, 하나빌딩 1층 (신당동)', 201341.792321443, 451246.571908878, '서울특별시 중구 신당동 102-6 ')
(22, '웰니스클리닉(청계천점)', '서울특별시 중구 청계천로 400, 지하 1층 (황학동, 롯데캐슬베네치아)', 201823.908977364, 452076.818664092, '서울특별시 중구 황학동 2545 롯데캐슬베네치아 ')
(23, '헬릭스동물심장수술센터', '서울특별시 중구 을지로38길 20, 뉴천지관광호텔 2층 (을지로5가)', 200225.983119633, 451511.262755282, '서울특별시 중구 을지로5가 133-1 뉴천지관광호텔 ')
(24, '헬릭스동물암센터', '서울특별시 중구 을지로38길 20, 뉴천지관광호텔 1층 (을지로5가)', 200225.983119633, 451511.262755282, '서울특별시 중구 을지로5가 133-1 뉴천지관광호텔 ')
(25, '서울동물영상종양센터', '서울특별시 중구 을지로38길 20, 뉴천지관광호텔 1층 (을지로5가)', 200225.983119633, 451511.262755282, '서울특별시 중구 을지로5가 133-1 뉴천지관광호텔 ')
(26, '웰튼동물의료센터', '서울특별시 중구 난계로 197, 1,2,4층 (황학동)', 201985.829607973, 451869.587314453, '서울특별시 중구 황학동 1596 ')
(27, '에스디(SD)동물영상센터,서울', '서울특별시 중구 왕십리로 407, B1-1호 (신당동, 신당 파인힐 하나유보라)', 202131.747052459, 451330.482879118, '서울특별시 중구 신당동 855 신당 파인힐 하나유보라 ')
(28, '에스디(SD)동물의료센터,서울', '서울특별시 중구 왕십리로 407, 신당 파인힐 하나유보라 B1층 03,04,05호 (신당동, 신당 파인힐 하나유보라)', 202131.747052459, 451330.482879118, '서울특별시 중구 신당동 855 신당 파인힐 하나유보라 ')
(29, '힐스타운 동물병원', '서울특별시 중구 다산로 32, 스포츠상가동 106-2호 (신당동, 남산타운)', 200750.455125653, 449638.824308081, '서울특별시 중구 신당동 844 남산타운 ')
(30, '바우미우동물병원', '서울특별시 중구 다산로 175, 명덕빌딩 (신당동)', 201064.963697104, 450779.720971036, '서울특별시 중구 신당동 336-3 명덕빌딩 ')
(31, '더베이스 동물피부과병원', '서울특별시 용산구 한강대로 95, B동 지하2층 263호 (한강로2가, 래미안용산 더 센트럴)', 197011.737528847, 447430.100250997, '서울특별시 용산구 한강로2가 422 래미안용산 더 센트럴 ')
(32, '청화종합동물병원', '서울특별시 용산구 장문로 18, 2층 (동빙고동)', 199254.608612617, 447354.661580526, '서울특별시 용산구 동빙고동 7-19 ')
(33, '펫토이동물병원', '서울특별시 용산구 대사관로 32 (한남동)', 200079.108817319, 447917.947059496, '서울특별시 용산구 한남동 653-26 ')
(34, '금강동물병원', '서울특별시 용산구 이촌로 300, 렉스상가 8-1,8-2호 (이촌동)', 198165.767858385, 446185.244544796, '서울특별시 용산구 이촌동 301-263 렉스상가 8-1,8-2호 ')
(35, '라온동물병원', '서울특별시 용산구 회나무로 7, 2층 (이태원동)', 198842.61612083, 448493.993525383, '서울특별시 용산구 이태원동 647 ')
(36, '아프리카동물병원', '서울특별시 용산구 후암로 32 (후암동)', 197980.868340519, 449605.434772664, '서울특별시 용산구 후암동 244-11 ')
(37, '엉클장동물병원', '서울특별시 용산구 백범로 341, A동 지상1층 106호 (원효로1가, 리첸시아 용산)', 197045.849468346, 448447.558967085, '서울특별시 용산구 원효로1가 133-3 리첸시아 용산 A동 106호')
(38, '펫동물병원', '서울특별시 용산구 백범로 285, 지상1층 (효창동)', 196490.844311727, 448594.448927151, '서울특별시 용산구 효창동 79-1 지상1층 ')
(39, '달래동물의료센터', '서울특별시 용산구 한남대로 76, 한남프라자 2층 (한남동)', 200506.187313451, 448146.173245501, '서울특별시 용산구 한남동 707-36 한남프라자 2층 ')
(40, '민트동물병원', '서울특별시 용산구 원효로 51, 119호 (산천동, 삼성테마트)', 195547.140326252, 447976.775939762, '서울특별시 용산구 산천동 202 삼성테마트 119호 ')
(41, '이태원동물병원', '서울특별시 용산구 녹사평대로 210, 지하1, 1, 2층층 일부호 (이태원동)', 198802.476070336, 448239.820740686, '서울특별시 용산구 이태원동 531 ')
(42, '퍼스동물병원', '서울특별시 용산구 신흥로 54, 106호 (용산동2가, 북동연립)', 198855.032090543, 448982.633361938, '서울특별시 용산구 용산동2가 45-1 106호 ')
(43, '좋아서하는 동물병원', '서울특별시 용산구 백범로 341, B동 지상1층 113,114호 (원효로1가, 리첸시아 용산)', 197045.849468346, 448447.558967085, '서울특별시 용산구 원효로1가 133-3 리첸시아 용산 B동 113,114호 ')
(44, '바다동물병원(Bada Animal Hospital)', '서울특별시 용산구 서빙고로 67, 지하1층 비21호 (용산동5가, 파크타워)', 197338.915067396, 446893.484429691, '서울특별시 용산구 용산동5가 24 파크타워 지하1층 비21호')
(45, '24시 시유동물메디컬센터', '서울특별시 용산구 이촌로64길 24, 지상1층 101호 (이촌동)', 197270.042278677, 446419.923247168, '서울특별시 용산구 이촌동 302-88 지상1층 101호 ')
(46, '베이동물병원', '서울특별시 용산구 이촌로 248, 11동 102호 (이촌동, 한강맨션)', 197722.571038558, 446344.591216568, '서울특별시 용산구 이촌동 300-23 한강맨션 11동 102호')
(47, '더힐동물의료센터', '서울특별시 용산구 독서당로 81-1, 아이리스프라자 지상3층 (한남동)', 200779.182, 448049.195666666, '서울특별시 용산구 한남동 29-6 아이리스프라자 지상3층 ')
(48, '원스동물병원', '서울특별시 용산구 청파로47길 16, 지상1층 (청파동2가)', 197234.131475852, 449191.560826572, '서울특별시 용산구 청파동2가 90-20 지상1층 ')
(49, '이상윤동물병원', '서울특별시 용산구 이촌로 248, 31동 105-2호 (이촌동, 한강맨션)', 197722.571038558, 446344.591216568, '서울특별시 용산구 이촌동 300-23 한강맨션 ')
(50, '에스동물병원', '서울특별시 용산구 서빙고로 17, 헤링턴스퀘어 센트럴파크 몰동 1146, 1147호 (한강로3가)', 197056.728931087, 447077.126289262, '서울특별시 용산구 한강로3가 98 ')
(51, '위런한방재활동물병원', '서울특별시 용산구 한강대로 95, 225호 (한강로2가, 래미안용산 더 센트럴)', 197011.737528847, 447430.100250997, '서울특별시 용산구 한강로2가 422 래미안용산 더 센트럴 225호')
(52, '한남심장내과동물병원', '서울특별시 용산구 독서당로 46, 111호 (한남동, 한남아이파크)', 200571.725921493, 447793.924058853, '서울특별시 용산구 한남동 828 한남아이파크 ')
(53, '용산마음동물병원', '서울특별시 용산구 백범로 340, 2층 (원효로2가)', 196979.093087733, 448380.524209959, '서울특별시 용산구 원효로2가 1-36 ')
(54, '남산동물병원', '서울특별시 용산구 후암로 51, 지상1층 (후암동)', 197907.242547187, 449803.89961095, '서울특별시 용산구 후암동 63-1 지상1층 ')
(55, '효창동물병원', '서울특별시 용산구 백범로 293 (효창동)', 196561.891893717, 448563.455747747, '서울특별시 용산구 효창동 70-11 ')
(56, '열린동물종합병원', '서울특별시 용산구 원효로 171, 신영빌딩 (원효로2가)', 196549.89584221, 448153.524398611, '서울특별시 용산구 원효로2가 84-10 신영빌딩 ')
(57, '원효종합동물병원', '서울특별시 용산구 새창로 122-2(용문동)', 196459.674190442, 448255.165737565, '서울특별시 용산구 용문동 25-36 ')
(58, '한사랑동물병원', '서울특별시 용산구 신흥로 36-1 (용산동2가)', 198816.63972746, 448827.72464503, '서울특별시 용산구 용산동2가 45-7 ')
(59, '중심동물병원', '서울특별시 성동구 마조로 55, 상가동 1층 119호 (마장동, 금호어울림아파트)', 203597.7587591, 451160.268443273, '서울특별시 성동구 마장동 821 금호어울림아파트 ')
(60, '평생피부과동물병원', '서울특별시 성동구 행당로 76, 110호 (행당동, 한진노변상가)', 202511.142930696, 450401.303715561, '서울특별시 성동구 행당동 346 한진노변상가 110호')
(61, '오렌지동물병원', '서울특별시 성동구 행당로8길 41-2 (행당동)', 202931.789940848, 450419.387012901, '서울특별시 성동구 행당동 322-100 ')
(62, '한빛동물병원', '서울특별시 성동구 금호산길 58(금호동2가)', 201657.926313791, 450119.508052252, '서울특별시 성동구 금호동2가 485-1 ')
(63, '아지동물병원', '서울특별시 성동구 독서당로 289 (금호동4가,지상1층)', 201790.117515658, 449530.70769686, '서울특별시 성동구 금호동4가 1108 지상1층 ')
(64, '24시센트럴동물메디컬센터', '서울특별시 성동구 고산자로 207 (행당동)', 202907.218919388, 450712.086716399, '서울특별시 성동구 행당동 318-36 ')
(65, '이윤세동물병원', '서울특별시 성동구 행당로 76, 한진노변상가 1,2층 108호109호203호 (행당동)', 202511.142930696, 450401.303715561, '서울특별시 성동구 행당동 346 한진노변상가 109호')
(66, '한양동물메디컬센터', '서울특별시 성동구 왕십리로 282 (행당동)', 203200.771278441, 450821.216569269, '서울특별시 성동구 행당동 226-3 ')
(67, '옥수수 동물병원', '서울특별시 성동구 독서당로40길 39, 어울림상가 301~304호 (옥수동)', 201538.05612719, 448894.755196992, '서울특별시 성동구 옥수동 560 어울림상가 301~4호')
(68, '도담동물병원(출장진료전문 동물병원)', '서울특별시 성동구 독서당로59길 84, 신동아아파트상가동 1층 111호 (행당동)', 202831.905687785, 450233.87834092, '서울특별시 성동구 행당동 344 111호')
(69, '라임동물병원', '서울특별시 성동구 무학로 16 (홍익동)', 202608.881117477, 451473.310104052, '서울특별시 성동구 홍익동 398-2 ')
(70, '바른동물병원', '서울특별시 성동구 독서당로 270, 상가동 2층 206호 (금호동4가, 금호동 대우아파트)', 201669.803556903, 449301.451523245, '서울특별시 성동구 금호동4가 800 금호동대우아파트 상가동 206호')
(71, '기린동물병원', '서울특별시 성동구 마장로 296 (마장동)', 203709.590135792, 451490.666502232, '서울특별시 성동구 마장동 791-9 ')
(72, '왕십리조은동물병원', '서울특별시 성동구 왕십리로 381 (하왕십리동)', 202393.457305335, 451365.326207693, '서울특별시 성동구 하왕십리동 892-4 ')
(73, '오석헌동물병원', '서울특별시 성동구 매봉길 13, 1층 420호 (옥수동, 래미안옥수리버젠상가)', 201153.981577199, 449188.97052419, '서울특별시 성동구 옥수동 561 래미안옥수리버젠 상가동 420호')
(74, '제인동물병원', '서울특별시 성동구 뚝섬로 395 (성수동2가)', 204763.80767636, 448534.113764965, '서울특별시 성동구 성수동2가 339-23 ')
(75, '금호동물병원', '서울특별시 성동구 금호로 105, 비201호 (금호동2가, 래미안하이리버 상가동)', 202098.97937718, 449891.972244601, '서울특별시 성동구 금호동2가 1217 래미안하이리버 상가동 비201호')
(76, '포레동물병원', '서울특별시 성동구 상원길 59, 쌍용아파트상가B동 107호 (성수동1가)', 204093.39625466, 449695.084129637, '서울특별시 성동구 성수동1가 706 쌍용아파트상가B동 107호')
(77, '스테이동물병원', '서울특별시 성동구 매봉길 50 (옥수동, 이편한세상옥수파크힐스)', 201157.877298502, 449563.280012747, '서울특별시 성동구 옥수동 528 이편한세상옥수파크힐스 ')
(78, '바라봄동물병원', '서울특별시 성동구 왕십리로 410, 127동 지하층 030호 (하왕십리동, 센트라스)', 202372.912023599, 451536.680876573, '')
(79, '달링동물병원', '서울특별시 성동구 왕십리로 16 (성수동1가, 트리마제)', 203911.513091074, 448508.756036449, '서울특별시 성동구 성수동1가 718 트리마제 ')
(80, '베이지동물병원', '서울특별시 성동구 왕십리로 410, D동 106호 (하왕십리동, 센트라스)', 202372.912023599, 451536.680876573, '서울특별시 성동구 하왕십리동 1070 센트라스상가 D동 106호')
(81, '오늘동물병원', '서울특별시 성동구 왕십리로 104, 영화빌딩 2층 (성수동1가)', 203895.448794593, 449401.289888823, '서울특별시 성동구 성수동1가 656-968 영화빌딩 2층 ')
(82, '조형선외과동물병원', '서울특별시 성동구 금호로 146, 제1, 2층 (금호동1가)', 201774.580419376, 450208.959848768, '서울특별시 성동구 금호동1가 526 ')
(83, 'BK심장동물병원', '서울특별시 성동구 고산자로6길 40, 행당동 레몬프라자 1층 113호 (행당동)', 203071.959180897, 450665.532604254, '서울특별시 성동구 행당동 140 행당동 레몬프라자 1층 113호')
(84, '성수 숲속 피부과 동물병원', '서울특별시 성동구 서울숲2길 32-14, 지하1층 B114호 (성수동1가, 갤러리아 포레)', 203684.281166499, 449280.97521227, '서울특별시 성동구 성수동1가 685-696 갤러리아 포레 지하1층 B114호')
(85, '왕십리동물병원', '서울특별시 성동구 무학로6길 50, 101동 225호 (도선동, 성동삼성쉐르빌)', 203017.021457357, 451346.281102634, '서울특별시 성동구 도선동 69 성동삼성쉐르빌 101동 225호')
(86, '보람동물병원', '서울특별시 광진구 군자로 84 (군자동)', 206218.599101694, 449808.490100535, '서울특별시 광진구 군자동 363-4 ')
(87, '애플동물병원', '서울특별시 광진구 천호대로 642-1 (능동)', 207733.266195381, 450105.913833549, '서울특별시 광진구 능동 256-1 ')
(88, '로엘동물병원', '서울특별시 광진구 뚝섬로 622-1 (자양동)', 206893.84345075, 447758.903010754, '서울특별시 광진구 자양동 606-14 ')
(89, '해맑은동물병원', '서울특별시 광진구 뚝섬로 670 (자양동)', 207349.510653919, 447708.939689927, '서울특별시 광진구 자양동 662-13 ')
(90, '노룬산동물병원', '서울특별시 광진구 뚝섬로 462 (자양동)', 205390.463339147, 448294.665199062, '서울특별시 광진구 자양동 236-127 ')
(91, '준동물병원', '서울특별시 광진구 뚝섬로 541 (자양동)', 206150.655471501, 448076.720689255, '서울특별시 광진구 자양동 553-588 ')
(92, '서울어린이대공원동물병원', '서울특별시 광진구 능동로 216 (능동)', 207139.204095368, 449705.67643744, '서울특별시 광진구 능동 18-0 ')
(93, '나루동물병원', '서울특별시 광진구 아차산로 537-17 (광장동)', 208729.170395929, 448995.808404463, '서울특별시 광진구 광장동 582 ')
(94, '다온동물병원', '서울특별시 광진구 면목로 142 (중곡동)', 207128.898416579, 451521.824189635, '서울특별시 광진구 중곡동 193-29 ')
(95, '자양동물병원', '서울특별시 광진구 뚝섬로52길 4 (자양동)', 206943.894875237, 447730.416384887, '서울특별시 광진구 자양동 606-27 ')
(96, '드림펫 동물병원', '서울특별시 광진구 능동로 407, 2층 (중곡동)', 207333.639771374, 451464.267096677, '서울특별시 광진구 중곡동 166-6 ')
(97, '서울동물병원', '서울특별시 광진구 천호대로 623-1, 1층 (중곡동)', 207624.556805359, 450257.044484869, '서울특별시 광진구 중곡동 119-7 ')
(98, '로얄 도그앤캣 메디컬센터', '서울특별시 광진구 능동로 49 (자양동, 영지빌딩)', 205969.966011569, 448175.917404606, '서울특별시 광진구 자양동 550-1 ')
(99, '파라곤동물병원', '서울특별시 광진구 광나루로 361, 2동 103호 (군자동, 광진동양파라곤)', 206091.938587177, 449581.249922815, '')
(100, '쿨펫동물병원', '서울특별시 광진구 아차산로 272 (자양동, 이마트 자양점)', 206349.675048285, 448396.939704285, '')
(101, '연두동물병원', '서울특별시 광진구 광나루로 524 (구의동)', 207679.128954008, 449166.073716992, '')
(102, '광진24시필동물병원', '서울특별시 광진구 광나루로56길 66, 201, 202호 (구의동)', 208403.746065593, 448490.239179557, '서울특별시 광진구 구의동 611 구의현대2단지아파트 ')
(103, '스마트동물병원군자점', '서울특별시 광진구 능동로43길 3-5 (중곡동)', 207107.928644491, 450953.281007512, '서울특별시 광진구 중곡동 162-8 ')
(104, '아이본 동물병원', '서울특별시 광진구 자양로 65, 화성빌딩 1층 (자양동)', 207386.983040962, 447934.708019366, '서울특별시 광진구 자양동 657-5 화성빌딩 1층 ')
(105, '우주동물병원', '서울특별시 광진구 자양로15길 30, 1층 (자양동)', 207169.000147705, 448162.523899287, '서울특별시 광진구 자양동 612-56 ')
(106, '다봄 동물병원', '서울특별시 광진구 자양로 163, 우남빌딩 (구의동)', 207334.35237407, 448890.470998334, '서울특별시 광진구 구의동 254-36 우남빌딩 1층 ')
(107, '아크로벳 내과동물병원', '서울특별시 광진구 광나루로 582, 세종빌딩 1층 (구의동)', 208181.517388785, 448984.848324887, '서울특별시 광진구 구의동 202-3 1층 ')
(108, '비비동물병원', '서울특별시 광진구 능동로 21, 1층 (자양동)', 205877.28221374, 447919.248318372, '서울특별시 광진구 자양동 65-1 ')
(109, '서울대학교동물검진센터', '서울특별시 광진구 구의강변로 46, 금성빌딩 1,2층 (구의동)', 208073.305054801, 448077.378533521, '서울특별시 광진구 구의동 594-4 금성빌딩 ')
(110, 'Severance AMC', '서울특별시 광진구 천호대로 512, 군자빌딩 b층 02호 (군자동)', 206582.005887061, 450685.591302855, '서울특별시 광진구 군자동 466-17 군자빌딩 ')
(111, '프라임동물병원', '서울특별시 광진구 아차산로 451 (구의동)', 208060.467769154, 448564.992528913, '서울특별시 광진구 구의동 659 세림리오빌아파트 제비1-1호')
(112, '동서울동물병원', '서울특별시 광진구 아차산로 493 (광장동)', 208431.92764385, 448842.232617503, '서울특별시 광진구 광장동 517-5 삼익아파트 ')
(113, '피카소동물병원', '서울특별시 광진구 광나루로 392-1 (화양동)', 206405.844680642, 449450.171000912, '서울특별시 광진구 화양동 216 ')
(114, '용마동물병원', '서울특별시 광진구 용마산로 66 (중곡동)', 207695.480720925, 450809.028344187, '서울특별시 광진구 중곡동 58-18 ')
(115, '중곡동물병원', '서울특별시 광진구 긴고랑로 47 (중곡동)', 207137.468593835, 451166.351150671, '서울특별시 광진구 중곡동 241-34 ')
(116, '방주종합동물병원', '서울특별시 광진구 능동로 334 (중곡동)', 207082.19653446, 450786.420735596, '서울특별시 광진구 중곡동 161-27 ')
(117, '광진동물의료센터', '서울특별시 광진구 광나루로 507 (구의동)', 207526.590151138, 449223.749584778, '서울특별시 광진구 구의동 68-37 ')
(118, '건국대학교 부속 동물병원', '서울특별시 광진구 능동로 120 (화양동)', 206445.881091692, 448922.881688102, '서울특별시 광진구 화양동 1 ')
(119, '쥬라기동물병원', '서울특별시 광진구 광나루로 601 (광장동)', 208344.912915338, 448875.286459939, '서울특별시 광진구 광장동 530-39 ')
(120, '이다종합동물병원', '서울특별시 광진구 뚝섬로 504 (자양동)', 205770.381275106, 448175.187322101, '서울특별시 광진구 자양동 553-280 ')
(121, '나래동물병원', '서울특별시 광진구 능동로 283 (군자동)', 206836.098040667, 450344.799584363, '서울특별시 광진구 군자동 1-2 ')
(122, '청량리 슬기 동물병원', '서울특별시 동대문구 왕산로 186, 청량리역 우남SL타워300 218, 219호 (전농동)', 203816.673034515, 453023.128996239, '서울특별시 동대문구 전농동 620-15 청량리역 우남SL타워300 ')
(123, '이즈 동물병원', '서울특별시 동대문구 이문로35길 12, 상가 C동 102호 (이문동, 래미안라그란데아파트)', 205249.265435832, 455308.651763587, '서울특별시 동대문구 이문동 257-42 래미안라그란데아파트 ')
(124, '아이랑 동물병원', '서울특별시 동대문구 이문로35길 12, 상가 A동 101호 (이문동, 래미안라그란데아파트)', 205249.265435832, 455308.651763587, '서울특별시 동대문구 이문동 257-42 래미안라그란데아파트 ')
(125, '심재웅동물병원', '서울특별시 동대문구 망우로 120 (휘경동)', 205804.989007148, 454312.287025523, '서울특별시 동대문구 휘경동 34-48 ')
(126, '박철환동물병원', '서울특별시 동대문구 사가정로 221 (장안동)', 206086.591362203, 452959.773010702, '서울특별시 동대문구 장안동 100-8 ')
(127, '뉴월드동물병원', '서울특별시 동대문구 한천로 94, 1층 (장안동)', 205631.56459772, 451925.907664051, '서울특별시 동대문구 장안동 186-12 ')
(128, '그랜드동물병원', '서울특별시 동대문구 전농로 77(답십리동)', 204974.829709532, 452169.781296696, '서울특별시 동대문구 답십리동 250-1 ')
(129, '애니케어동물병원', '서울특별시 동대문구 이문로 80 (이문동)', 205129.365335764, 454637.821983342, '서울특별시 동대문구 이문동 324-3 ')
(130, '푸른종합동물병원', '서울특별시 동대문구 홍릉로 48-1, 1층 (청량리동)', 203823.018467941, 453587.707759897, '서울특별시 동대문구 청량리동 359 ')
(131, '장평25시동물종합병원', '서울특별시 동대문구 장한로 139 (장안동)', 206237.158132452, 452292.449080256, '서울특별시 동대문구 장안동 307-3 ')
(132, '안암동물병원', '서울특별시 동대문구 안암로 40, 1층 (용두동)', 202296.946950935, 453139.055096553, '서울특별시 동대문구 용두동 732-5 ')
(133, '주주동물병원', '서울특별시 동대문구 사가정로 121 (전농동)', 205096.03189952, 452842.927086522, '서울특별시 동대문구 전농동 38-24 ')
(134, '맑은 동물병원', '서울특별시 동대문구 청계천로 417, 108호 (신설동, 청계천 대성 스카이렉스1)', 202042.817335648, 452190.100421552, '서울특별시 동대문구 신설동 109-13 청계천 대성 스카이렉스1 ')
(135, '그린동물병원', '서울특별시 동대문구 정릉천동로 58, 1층 125호 (용두동, 롯데캐슬피렌체)', 203085.866786086, 452766.014195644, '서울특별시 동대문구 용두동 790 롯데캐슬피렌체 ')
(136, '엘동물병원', '서울특별시 동대문구 고산자로 393-5 (용두동)', 203254.520083136, 452487.042671279, '서울특별시 동대문구 용두동 38-17 ')
(137, '제연동물병원', '서울특별시 동대문구 답십리로 77 (전농동)', 204313.869527831, 452538.14193671, '서울특별시 동대문구 전농동 652-1 ')
(138, 'VIP동물의료센터 동대문점', '서울특별시 동대문구 한천로14길 87(장안동)', 205899.907023899, 451571.351779533, '서울특별시 동대문구 장안동 376-3 ')
(139, '페트로동물의료원', '서울특별시 동대문구 답십리로63길 1(장안동)', 205911.321964079, 452287.844106267, '서울특별시 동대문구 장안동 140-8 ')
(140, '하나동물병원', '서울특별시 동대문구 망우로 66 (휘경동)', 205314.479215834, 454133.191843723, '서울특별시 동대문구 휘경동 267-84 ')
(141, '봄봄동물병원', '서울특별시 동대문구 회기로18길 46 (회기동)', 204704.034122842, 454227.304386333, '서울특별시 동대문구 회기동 62-8 ')
(142, '아띠동물의료센터', '서울특별시 동대문구 사가정로 51 (전농동)', 204553.458408807, 452384.461701131, '서울특별시 동대문구 전농동 322-31 ')
(143, '스마트동물병원', '서울특별시 동대문구 한천로 164, 1층 (장안동)', 205908.898385821, 452581.997774717, '서울특별시 동대문구 장안동 483 ')
(144, '바론동물병원', '서울특별시 동대문구 이문로 136, 2층 208호 (이문동, 이문동 웰츠타워)', 205396.363734301, 455131.683241064, '서울특별시 동대문구 이문동 292-10 이문동 웰츠타워 ')
(145, '더케이동물병원', '서울특별시 동대문구 답십리로 140, 세기프라자 2층 211호 (답십리동)', 204845.874285687, 452243.87695363, '서울특별시 동대문구 답십리동 1003-2 세기프라자 ')
(146, '현대종합동물병원', '서울특별시 동대문구 답십리로 293, 1층 (장안동)', 206384.176300093, 452248.684634996, '서울특별시 동대문구 장안동 330-2 ')
(147, '하이유 동물병원', '서울특별시 동대문구 전농로 15-3 (답십리동)', 204869.688144425, 451594.33252299, '서울특별시 동대문구 답십리동 490-57 ')
(148, '아인스동물병원', '서울특별시 동대문구 장한로 44, 1층 (장안동)', 205883.994796584, 451422.978298566, '서울특별시 동대문구 장안동 435-6 ')
(149, '아이원 동물병원', '서울특별시 동대문구 전농로 80, 1층 (답십리동)', 205018.210432587, 452185.824073309, '서울특별시 동대문구 답십리동 52-3 ')
(150, '땅콩동물병원', '서울특별시 동대문구 답십리로 224-1 (답십리동)', 205696.046346636, 452256.64849964, '서울특별시 동대문구 답십리동 3-125 ')
(151, '24시 동대문 루시드 동물메디컬센터', '서울특별시 동대문구 전농로 57-1, 1층,2층,지하1층 동대문 루시드 동물메디컬센터 (답십리동)', 204958.890769622, 451983.572742918, '서울특별시 동대문구 답십리동 259-22 ')
(152, '서울동물복지지원센터 동대문 동물병원', '서울특별시 동대문구 무학로 201 (용두동)', 202523.469147286, 453317.110098416, '서울특별시 동대문구 용두동 726-1 ')
(153, '진서동물병원', '서울특별시 중랑구 신내로10길 7 (신내동)', 208400.763171651, 455823.471989854, '서울특별시 중랑구 신내동 571-8 ')
(154, '세진동물병원', '서울특별시 중랑구 망우로 415(망우동)', 208613.331372822, 455266.331938295, '서울특별시 중랑구 망우동 488-14 ')
(155, '숲속동물병원', '서울특별시 중랑구 겸재로 207, 1층 (면목동)', 207928.911342193, 454115.499601712, '서울특별시 중랑구 면목동 103-4 1층 ')
(156, '면목동물병원', '서울특별시 중랑구 사가정로 363 (면목동)', 207429.833336087, 453216.12116107, '서울특별시 중랑구 면목동 606-6 ')
(157, '하니동물병원', '서울특별시 중랑구 신내로 225, 디아뜨갤러리 142호 (신내동)', 207990.479257211, 457183.637796144, '서울특별시 중랑구 신내동 648 디아뜨갤러리 ')
(158, '한국동물메디컬센터(KAMC)', '서울특별시 중랑구 겸재로 165, 1,2층 (면목동)', 207517.256308479, 453990.823070309, '서울특별시 중랑구 면목동 119-10 1,2층 ')
(159, '닥터 아이펫 동물병원', '서울특별시 중랑구 망우로 315, 2층 (상봉동)', 207655.291092379, 454993.657588592, '서울특별시 중랑구 상봉동 99-10 ')
(160, '행복이 있는 동물병원', '서울특별시 중랑구 봉화산로 232, B동 1층 (신내동)', 208614.435553033, 456169.871765864, '서울특별시 중랑구 신내동 405-5 ')
(161, '보담동물병원', '서울특별시 중랑구 용마산로 434 (면목동, 청파빌딩)', 208533.165197782, 454186.696918605, '서울특별시 중랑구 면목동 17-31 ')
(162, '로얄동물암치료센터', '서울특별시 중랑구 동일로 640, 지하 2층 (면목동)', 207017.81527047, 453914.639780644, '서울특별시 중랑구 면목동 146-75 ')
(163, '아이봄 동물병원', '서울특별시 중랑구 신내로 66 (신내동)', 208374.549467469, 455862.278991004, '서울특별시 중랑구 신내동 563-2 ')
(164, '레미 동물병원', '서울특별시 중랑구 동일로 593, 2층 (면목동)', 206949.692364552, 453453.28377601, '서울특별시 중랑구 면목동 172-93 ')
(165, '치료해주오 동물병원 중랑묵동점', '서울특별시 중랑구 동일로 925, 3층 (묵동)', 206712.645739265, 456738.441211434, '서울특별시 중랑구 묵동 238-8 하태윤산부인과 ')
(166, '닥터멍동물병원', '서울특별시 중랑구 상봉로 17, 1층 (면목동)', 208243.910432602, 453913.946459696, '서울특별시 중랑구 면목동 71-41 ')
(167, '로얄동물메디컬센터 본원', '서울특별시 중랑구 동일로 640, 2층, 3층 (면목동)', 207017.81527047, 453914.639780644, '서울특별시 중랑구 면목동 146-75 ')
(168, '로얄동물외과수술센터', '서울특별시 중랑구 동일로 640, 지하1, 지상4층 (면목동)', 207017.81527047, 453914.639780644, '서울특별시 중랑구 면목동 146-75 ')
(169, '혜원동물병원', '서울특별시 중랑구 면목로 341, 1층 (면목동)', 207729.175659582, 453342.232542102, '서울특별시 중랑구 면목동 497-7 ')
(170, '중랑차동물병원', '서울특별시 중랑구 중랑천로 81, 101호 (상봉동)', 206345.47354923, 454460.821850917, '서울특별시 중랑구 상봉동 137-16 ')

In [16]:
cursor.execute("SELECT * FROM hospital WHERE new_address LIKE '%영등포%'")
rows = cursor.fetchall()

for row in rows:
    print(row)

(582, '24시여의동물의료센터', '서울특별시 영등포구 국회대로74길 4, KCTOWER 1층 (여의도동)', 192914.020706344, 447594.120761002, '서울특별시 영등포구 여의도동 13-13 KCTOWER ')
(583, '서울 스템셀 동물병원', '서울특별시 영등포구 의사당대로 38, 101-105호 (여의도동)', 192747.419300064, 447054.988337321, '서울특별시 영등포구 여의도동 17 여의도더샵아일랜드파크 ')
(584, '포커스동물의료센터', '서울특별시 영등포구 신풍로 28, 제에코동 지하1층 제비128~131호 (신길동, 비스타동원)', '', '', '서울특별시 영등포구 신길동 4975 비스타동원 제에코동 제비128호')
(585, '대방동물병원', '서울특별시 영등포구 신풍로25길 13, 그레이트 빌 1층 (신길동)', 192854.528260001, 444333.005548234, '서울특별시 영등포구 신길동 583 그레이트 빌 ')
(586, '신풍동물종합병원', '서울특별시 영등포구 신길로 70 (신길동)', 191844.925514769, 444053.006856572, '서울특별시 영등포구 신길동 3611 ')
(587, '참 동물병원', '서울특별시 영등포구 영등포로76길 1 (신길동)', 192844.105439729, 445716.610165853, '서울특별시 영등포구 신길동 95-39 ')
(588, '우신종합동물병원', '서울특별시 영등포구 신길로 168 (신길동)', 192081.391357898, 445002.688462087, '서울특별시 영등포구 신길동 232-15 ')
(589, '서울동물병원', '서울특별시 영등포구 영중로27길 10 (영등포동7가)', 191465.892560136, 446905.037998287, '서울특별시 영등포구 영등포동7가 64-48 ')
(590, '애드펫동물병원', '서울특별시 영등포구 선유서로 67, 신동아하이팰리스상가 104동 131호 (양평동2가)', 189734.544016734, 446634.254586356, '서울특별시 영등포구 양평동2가 1-1 신동아하이팰리스 ')
(591, '디오빌 동물병원', '서울특별시 영등포구 당산로 222, 1층 103-3호 (당산동5가, 당산디오빌)', 191292.095160096, 447892.078672003, '서울특별시 영등포구 당산동5가 11-33 당산디오빌 ')
(592, 'Dr.수동물병원', '서울특별시 영등포구 국제금융로 79, 롯데슈퍼 2층 (여의도동, 한양아파트)', 193963.563089797, 446584.550237569, '서울특별시 영등포구 여의도동 42 한양아파트 ')
(593, '온누리 종합동물병원', '서울특별시 영등포구 도신로 186, 2층 (신길동)', 192153.621514206, 445405.23699102, '서울특별시 영등포구 신길동 214-55 ')
(594, '유석동물병원', '서울특별시 영등포구 여의대방로 11 (신길동)', 191954.131669663, 443477.984573011, '서울특별시 영등포구 신길동 4824 ')
(595, 'I-pet 동물병원', '서울특별시 영등포구 여의동로3길 10, 501동 109호 (여의도동, 여의도자이)', 193393.096553574, 446218.443828439, '서울특별시 영등포구 여의도동 47 여의도자이 ')
(596, '왈츠동물병원', '서울특별시 영등포구 가마산로 324 (대림동)', 190691.328339211, 444029.182337058, '서울특별시 영등포구 대림동 776-2 ')
(597, '도그플러스동물병원', '서울특별시 영등포구 당산로 42, 4층 (문래동3가, 삼성홈플러스빌딩)', 190729.506453391, 446227.07504062, '서울특별시 영등포구 문래동3가 55-3 4층 ')
(598, '영등포동물병원', '서울특별시 영등포구 영등포로 131-2 (당산동1가)', 190759.061831054, 446595.928725552, '서울특별시 영등포구 당산동1가 40-18 ')
(599, '한가람동물의료센터', '서울특별시 영등포구 도신로 252 (신길동)', 192727.874792619, 445692.92673388, '서울특별시 영등포구 신길동 100-12 중양빌딩 ')
(600, '미소로동물병원', '서울특별시 영등포구 영신로 238, 미소로 107,108,204호 (영등포동8가)', 191463.486635133, 447373.174522815, '서울특별시 영등포구 영등포동8가 72 미소로 ')
(601, '경인동물의료센터', '서울특별시 영등포구 경인로114길 6, 202호, 상가301호 (영등포동1가, 여의도 이튼브라운)', 192256.642719075, 446248.646324888, '서울특별시 영등포구 영등포동1가 92-3 여의도 이튼브라운 202호, 상가301호 ')
(602, '아람동물병원', '서울특별시 영등포구 도신로 225-1, 1층 (신길동, 정일빌딩)', 192500.495045235, 445551.115998532, '서울특별시 영등포구 신길동 162-10 ')
(603, '여의도 동물병원', '서울특별시 영등포구 국제금융로 108, 4층 (여의도동, 미라클빌딩)', 194056.681860495, 446279.083804498, '서울특별시 영등포구 여의도동 53-3 미라클빌딩 4층 ')
(604, '이든동물의료센터', '서울특별시 영등포구 양평로 5, 1,2층 (당산동5가, 성원빌딩)', 191537.003577809, 447765.030228458, '서울특별시 영등포구 당산동5가 11-30 1,2층 ')
(605, '신길 온동물병원', '서울특별시 영등포구 신풍로 77, 상가동 C119호 (신길동, 래미안에스티움)', 192287.059579022, 444303.222020427, '서울특별시 영등포구 신길동 2039 상가동 C119호')
(606, '24시 수 동물메디컬센터', '서울특별시 영등포구 영등포로 85-1, 지층,1,2,3층 (양평동1가)', 190309.663767451, 446683.974500419, '서울특별시 영등포구 양평동1가 28-3 ')
(607, '그림책 읽어주는 동물병원', '서울특별시 영등포구 당산로36길 12, 111호 (당산동4가, 당산2차삼성아파트)', 190952.393621063, 447295.214623263, '서울특별시 영등포구 당산동4가 94-1 당산2차삼성아파트 ')
(608, '라이프 동물병원', '서울특별시 영등포구 가마산로 442, 상가동 B207, 208호 (신길동, 래미안프레비뉴)', 191810.315721141, 444749.050812048, '서울특별시 영등포구 신길동 4945 래미안프레비뉴 ')
(609, '영등포아크로 동물병원', '서울특별시 영등포구 국회대로54길 10, 근린생활시설 6동 2호 (영등포동7가, 아크로타워 스퀘어)', 191687.492947271, 446910.540802457, '서울특별시 영등포구 영등포동7가 203 아크로타워 스퀘어 ')
(610, '캣앤캣 고양이 병원', '서울특별시 영등포구 선유로 76, 동국메뜨리앙 206호 (문래동3가)', 190199.2294276, 446496.865300952, '서울특별시 영등포구 문래동3가 84-2 동국메뜨리앙 ')
(611, '러브펫 동물병원', '서울특별시 영등포구 영중로 15, 타임스퀘어 지하층 B104호 (영등포동4가)', 191385.057392247, 446098.555926507, '서울특별시 영등포구 영등포동4가 442 타임스퀘어 ')
(612, '플러스동물메디컬센터', '서울특별시 영등포구 양평로12가길 14, 르네상스 한강 오피스텔 1층 103호 (양평동4가)', 191060.688283317, 448289.617887109, '서울특별시 영등포구 양평동4가 281 르네상스 한강 오피스텔 ')
(613, '시그널동물병원', '서울특별시 영등포구 신길로 119, 112동 비103호,비104호,비105호 (신길동, 신길뉴타운 한화 꿈에그린)', 191937.554563608, 444531.729194913, '서울특별시 영등포구 신길동 4937 신길뉴타운 한화 꿈에그린 ')
(614, '다움동물병원', '서울특별시 영등포구 가마산로 449-1, 영민빌딩 1층 (신길동)', 191647.162754919, 444844.764072362, '서울특별시 영등포구 신길동 324-49 영민빌딩 1층 ')
(615, '도림하나동물병원', '서울특별시 영등포구 도영로 31, 1층 (도림동)', 190789.720923955, 445203.749465884, '서울특별시 영등포구 도림동 216-2 ')
(616, '동물병원예지', '서울특별시 영등포구 신길로 29, 105동 116호 (대림동, e편한세상 영등포 아델포레)', 191711.319229969, 443582.203546963, '서울특별시 영등포구 대림동 1127 e편한세상 영등포 아델포레 ')
(617, '김앤정동물병원', '서울특별시 영등포구 선유로 52, 1층 우측호 (문래동3가)', 190148.374147923, 446256.213232429, '서울특별시 영등포구 문래동3가 77-45 ')
(618, '신길S동물의료센터', '서울특별시 영등포구 도신로 86, 1층 (신길동)', 191259.378434391, 444946.729697606, '서울특별시 영등포구 신길동 362-22 ')
(619, '헬로우동물병원 여의도점', '서울특별시 영등포구 국제금융로7길 22, 대교B상가 2층 202호 (여의도동)', 194015.180457719, 446777.454528971, '서울특별시 영등포구 여의도동 41-1 대교B상가 202호')
(620, '엘림동물병원', '서울특별시 영등포구 가마산로 584, 제흥한의원 1층 (신길동)', 192955.313671889, 444637.094833567, '서울특별시 영등포구 신길동 720 제흥한의원 ')
(621, '동물의료센터24인치', '서울특별시 영등포구 가마산로 496, JS타워 205~207,303~304,306~307호 (신길동)', 192103.614282017, 444816.002381357, '서울특별시 영등포구 신길동 236 JS타워 ')

In [17]:
big = '서울'
small = '영등포구'

cursor.execute("""
    SELECT *
    FROM hospital
    WHERE new_address LIKE ?
      AND new_address LIKE ?
""", (f"{big}%", f"%{small}%"))

rows = cursor.fetchall()

for row in rows:
    print(row)

(582, '24시여의동물의료센터', '서울특별시 영등포구 국회대로74길 4, KCTOWER 1층 (여의도동)', 192914.020706344, 447594.120761002, '서울특별시 영등포구 여의도동 13-13 KCTOWER ')
(583, '서울 스템셀 동물병원', '서울특별시 영등포구 의사당대로 38, 101-105호 (여의도동)', 192747.419300064, 447054.988337321, '서울특별시 영등포구 여의도동 17 여의도더샵아일랜드파크 ')
(584, '포커스동물의료센터', '서울특별시 영등포구 신풍로 28, 제에코동 지하1층 제비128~131호 (신길동, 비스타동원)', '', '', '서울특별시 영등포구 신길동 4975 비스타동원 제에코동 제비128호')
(585, '대방동물병원', '서울특별시 영등포구 신풍로25길 13, 그레이트 빌 1층 (신길동)', 192854.528260001, 444333.005548234, '서울특별시 영등포구 신길동 583 그레이트 빌 ')
(586, '신풍동물종합병원', '서울특별시 영등포구 신길로 70 (신길동)', 191844.925514769, 444053.006856572, '서울특별시 영등포구 신길동 3611 ')
(587, '참 동물병원', '서울특별시 영등포구 영등포로76길 1 (신길동)', 192844.105439729, 445716.610165853, '서울특별시 영등포구 신길동 95-39 ')
(588, '우신종합동물병원', '서울특별시 영등포구 신길로 168 (신길동)', 192081.391357898, 445002.688462087, '서울특별시 영등포구 신길동 232-15 ')
(589, '서울동물병원', '서울특별시 영등포구 영중로27길 10 (영등포동7가)', 191465.892560136, 446905.037998287, '서울특별시 영등포구 영등포동7가 64-48 ')
(590, '애드펫동물병원', '서울특별시 영등포구 선유서로 67, 신동아하이팰리스상가 104동 131호 (양평동2가)', 189734.544016734, 446634.254586356, '서울특별시 영등포구 양평동2가 1-1 신동아하이팰리스 ')
(591, '디오빌 동물병원', '서울특별시 영등포구 당산로 222, 1층 103-3호 (당산동5가, 당산디오빌)', 191292.095160096, 447892.078672003, '서울특별시 영등포구 당산동5가 11-33 당산디오빌 ')
(592, 'Dr.수동물병원', '서울특별시 영등포구 국제금융로 79, 롯데슈퍼 2층 (여의도동, 한양아파트)', 193963.563089797, 446584.550237569, '서울특별시 영등포구 여의도동 42 한양아파트 ')
(593, '온누리 종합동물병원', '서울특별시 영등포구 도신로 186, 2층 (신길동)', 192153.621514206, 445405.23699102, '서울특별시 영등포구 신길동 214-55 ')
(594, '유석동물병원', '서울특별시 영등포구 여의대방로 11 (신길동)', 191954.131669663, 443477.984573011, '서울특별시 영등포구 신길동 4824 ')
(595, 'I-pet 동물병원', '서울특별시 영등포구 여의동로3길 10, 501동 109호 (여의도동, 여의도자이)', 193393.096553574, 446218.443828439, '서울특별시 영등포구 여의도동 47 여의도자이 ')
(596, '왈츠동물병원', '서울특별시 영등포구 가마산로 324 (대림동)', 190691.328339211, 444029.182337058, '서울특별시 영등포구 대림동 776-2 ')
(597, '도그플러스동물병원', '서울특별시 영등포구 당산로 42, 4층 (문래동3가, 삼성홈플러스빌딩)', 190729.506453391, 446227.07504062, '서울특별시 영등포구 문래동3가 55-3 4층 ')
(598, '영등포동물병원', '서울특별시 영등포구 영등포로 131-2 (당산동1가)', 190759.061831054, 446595.928725552, '서울특별시 영등포구 당산동1가 40-18 ')
(599, '한가람동물의료센터', '서울특별시 영등포구 도신로 252 (신길동)', 192727.874792619, 445692.92673388, '서울특별시 영등포구 신길동 100-12 중양빌딩 ')
(600, '미소로동물병원', '서울특별시 영등포구 영신로 238, 미소로 107,108,204호 (영등포동8가)', 191463.486635133, 447373.174522815, '서울특별시 영등포구 영등포동8가 72 미소로 ')
(601, '경인동물의료센터', '서울특별시 영등포구 경인로114길 6, 202호, 상가301호 (영등포동1가, 여의도 이튼브라운)', 192256.642719075, 446248.646324888, '서울특별시 영등포구 영등포동1가 92-3 여의도 이튼브라운 202호, 상가301호 ')
(602, '아람동물병원', '서울특별시 영등포구 도신로 225-1, 1층 (신길동, 정일빌딩)', 192500.495045235, 445551.115998532, '서울특별시 영등포구 신길동 162-10 ')
(603, '여의도 동물병원', '서울특별시 영등포구 국제금융로 108, 4층 (여의도동, 미라클빌딩)', 194056.681860495, 446279.083804498, '서울특별시 영등포구 여의도동 53-3 미라클빌딩 4층 ')
(604, '이든동물의료센터', '서울특별시 영등포구 양평로 5, 1,2층 (당산동5가, 성원빌딩)', 191537.003577809, 447765.030228458, '서울특별시 영등포구 당산동5가 11-30 1,2층 ')
(605, '신길 온동물병원', '서울특별시 영등포구 신풍로 77, 상가동 C119호 (신길동, 래미안에스티움)', 192287.059579022, 444303.222020427, '서울특별시 영등포구 신길동 2039 상가동 C119호')
(606, '24시 수 동물메디컬센터', '서울특별시 영등포구 영등포로 85-1, 지층,1,2,3층 (양평동1가)', 190309.663767451, 446683.974500419, '서울특별시 영등포구 양평동1가 28-3 ')
(607, '그림책 읽어주는 동물병원', '서울특별시 영등포구 당산로36길 12, 111호 (당산동4가, 당산2차삼성아파트)', 190952.393621063, 447295.214623263, '서울특별시 영등포구 당산동4가 94-1 당산2차삼성아파트 ')
(608, '라이프 동물병원', '서울특별시 영등포구 가마산로 442, 상가동 B207, 208호 (신길동, 래미안프레비뉴)', 191810.315721141, 444749.050812048, '서울특별시 영등포구 신길동 4945 래미안프레비뉴 ')
(609, '영등포아크로 동물병원', '서울특별시 영등포구 국회대로54길 10, 근린생활시설 6동 2호 (영등포동7가, 아크로타워 스퀘어)', 191687.492947271, 446910.540802457, '서울특별시 영등포구 영등포동7가 203 아크로타워 스퀘어 ')
(610, '캣앤캣 고양이 병원', '서울특별시 영등포구 선유로 76, 동국메뜨리앙 206호 (문래동3가)', 190199.2294276, 446496.865300952, '서울특별시 영등포구 문래동3가 84-2 동국메뜨리앙 ')
(611, '러브펫 동물병원', '서울특별시 영등포구 영중로 15, 타임스퀘어 지하층 B104호 (영등포동4가)', 191385.057392247, 446098.555926507, '서울특별시 영등포구 영등포동4가 442 타임스퀘어 ')
(612, '플러스동물메디컬센터', '서울특별시 영등포구 양평로12가길 14, 르네상스 한강 오피스텔 1층 103호 (양평동4가)', 191060.688283317, 448289.617887109, '서울특별시 영등포구 양평동4가 281 르네상스 한강 오피스텔 ')
(613, '시그널동물병원', '서울특별시 영등포구 신길로 119, 112동 비103호,비104호,비105호 (신길동, 신길뉴타운 한화 꿈에그린)', 191937.554563608, 444531.729194913, '서울특별시 영등포구 신길동 4937 신길뉴타운 한화 꿈에그린 ')
(614, '다움동물병원', '서울특별시 영등포구 가마산로 449-1, 영민빌딩 1층 (신길동)', 191647.162754919, 444844.764072362, '서울특별시 영등포구 신길동 324-49 영민빌딩 1층 ')
(615, '도림하나동물병원', '서울특별시 영등포구 도영로 31, 1층 (도림동)', 190789.720923955, 445203.749465884, '서울특별시 영등포구 도림동 216-2 ')
(616, '동물병원예지', '서울특별시 영등포구 신길로 29, 105동 116호 (대림동, e편한세상 영등포 아델포레)', 191711.319229969, 443582.203546963, '서울특별시 영등포구 대림동 1127 e편한세상 영등포 아델포레 ')
(617, '김앤정동물병원', '서울특별시 영등포구 선유로 52, 1층 우측호 (문래동3가)', 190148.374147923, 446256.213232429, '서울특별시 영등포구 문래동3가 77-45 ')
(618, '신길S동물의료센터', '서울특별시 영등포구 도신로 86, 1층 (신길동)', 191259.378434391, 444946.729697606, '서울특별시 영등포구 신길동 362-22 ')
(619, '헬로우동물병원 여의도점', '서울특별시 영등포구 국제금융로7길 22, 대교B상가 2층 202호 (여의도동)', 194015.180457719, 446777.454528971, '서울특별시 영등포구 여의도동 41-1 대교B상가 202호')
(620, '엘림동물병원', '서울특별시 영등포구 가마산로 584, 제흥한의원 1층 (신길동)', 192955.313671889, 444637.094833567, '서울특별시 영등포구 신길동 720 제흥한의원 ')
(621, '동물의료센터24인치', '서울특별시 영등포구 가마산로 496, JS타워 205~207,303~304,306~307호 (신길동)', 192103.614282017, 444816.002381357, '서울특별시 영등포구 신길동 236 JS타워 ')

In [18]:
con = sqlite3.connect('../data/hospital.db')
cursor = con.cursor()
small = '중랑'
cursor.execute("SELECT * FROM hospital WHERE new_address LIKE ?", (f"%{small}%",))
#cursor.execute("SELECT * FROM hospital WHERE old_address LIKE '%중랑%'")
rows = cursor.fetchall()
for row in rows:
    print(row)

(153, '진서동물병원', '서울특별시 중랑구 신내로10길 7 (신내동)', 208400.763171651, 455823.471989854, '서울특별시 중랑구 신내동 571-8 ')
(154, '세진동물병원', '서울특별시 중랑구 망우로 415(망우동)', 208613.331372822, 455266.331938295, '서울특별시 중랑구 망우동 488-14 ')
(155, '숲속동물병원', '서울특별시 중랑구 겸재로 207, 1층 (면목동)', 207928.911342193, 454115.499601712, '서울특별시 중랑구 면목동 103-4 1층 ')
(156, '면목동물병원', '서울특별시 중랑구 사가정로 363 (면목동)', 207429.833336087, 453216.12116107, '서울특별시 중랑구 면목동 606-6 ')
(157, '하니동물병원', '서울특별시 중랑구 신내로 225, 디아뜨갤러리 142호 (신내동)', 207990.479257211, 457183.637796144, '서울특별시 중랑구 신내동 648 디아뜨갤러리 ')
(158, '한국동물메디컬센터(KAMC)', '서울특별시 중랑구 겸재로 165, 1,2층 (면목동)', 207517.256308479, 453990.823070309, '서울특별시 중랑구 면목동 119-10 1,2층 ')
(159, '닥터 아이펫 동물병원', '서울특별시 중랑구 망우로 315, 2층 (상봉동)', 207655.291092379, 454993.657588592, '서울특별시 중랑구 상봉동 99-10 ')
(160, '행복이 있는 동물병원', '서울특별시 중랑구 봉화산로 232, B동 1층 (신내동)', 208614.435553033, 456169.871765864, '서울특별시 중랑구 신내동 405-5 ')
(161, '보담동물병원', '서울특별시 중랑구 용마산로 434 (면목동, 청파빌딩)', 208533.165197782, 454186.696918605, '서울특별시 중랑구 면목동 17-31 ')
(162, '로얄동물암치료센터', '서울특별시 중랑구 동일로 640, 지하 2층 (면목동)', 207017.81527047, 453914.639780644, '서울특별시 중랑구 면목동 146-75 ')
(163, '아이봄 동물병원', '서울특별시 중랑구 신내로 66 (신내동)', 208374.549467469, 455862.278991004, '서울특별시 중랑구 신내동 563-2 ')
(164, '레미 동물병원', '서울특별시 중랑구 동일로 593, 2층 (면목동)', 206949.692364552, 453453.28377601, '서울특별시 중랑구 면목동 172-93 ')
(165, '치료해주오 동물병원 중랑묵동점', '서울특별시 중랑구 동일로 925, 3층 (묵동)', 206712.645739265, 456738.441211434, '서울특별시 중랑구 묵동 238-8 하태윤산부인과 ')
(166, '닥터멍동물병원', '서울특별시 중랑구 상봉로 17, 1층 (면목동)', 208243.910432602, 453913.946459696, '서울특별시 중랑구 면목동 71-41 ')
(167, '로얄동물메디컬센터 본원', '서울특별시 중랑구 동일로 640, 2층, 3층 (면목동)', 207017.81527047, 453914.639780644, '서울특별시 중랑구 면목동 146-75 ')
(168, '로얄동물외과수술센터', '서울특별시 중랑구 동일로 640, 지하1, 지상4층 (면목동)', 207017.81527047, 453914.639780644, '서울특별시 중랑구 면목동 146-75 ')
(169, '혜원동물병원', '서울특별시 중랑구 면목로 341, 1층 (면목동)', 207729.175659582, 453342.232542102, '서울특별시 중랑구 면목동 497-7 ')
(170, '중랑차동물병원', '서울특별시 중랑구 중랑천로 81, 101호 (상봉동)', 206345.47354923, 454460.821850917, '서울특별시 중랑구 상봉동 137-16 ')
(171, '산들동물병원', '서울특별시 중랑구 용마산로 670, C동 129,130호 (망우동, 신내역 프라디움 더 테라스)', 208947.072330515, 456501.735079654, '서울특별시 중랑구 망우동 584 신내역 프라디움 더 테라스 ')
(172, '모루 동물의료센터', '서울특별시 중랑구 망우로 373, 1층 (상봉동)', 208199.991565216, 455149.744971697, '서울특별시 중랑구 상봉동 74-43 ')
(173, '태능동물병원', '서울특별시 중랑구 동일로 920, 3층 (묵동)', 206780.207620819, 456698.48946494, '서울특별시 중랑구 묵동 175-2 3층 ')
(174, '보람동물병원', '서울특별시 중랑구 면목로 269 (면목동)', 207505.353493377, 452751.137837689, '서울특별시 중랑구 면목동 353-4 ')
(175, '엔젤동물병원', '서울특별시 중랑구 겸재로 187 (면목동)', 207735.456233727, 454057.837624796, '서울특별시 중랑구 면목동 102-51 ')
(176, '홍상희동물병원', '서울특별시 중랑구 동일로 899, 1층 (묵동)', 206763.653496703, 456484.166451356, '서울특별시 중랑구 묵동 239-76 ')
(177, '하스펫탈동물병원', '서울특별시 중랑구 면목로 442-1, 1층 (면목동)', 207610.403324186, 454365.747238549, '서울특별시 중랑구 면목동 225-7 ')
(178, '신내동물병원', '서울특별시 중랑구 봉화산로 103, 1층 (중화동, 삼일시티빌)', 207499.721342162, 455602.490288206, '서울특별시 중랑구 중화동 11-36 삼일시티빌 1층 ')
(179, '진정훈동물병원', '서울특별시 중랑구 봉화산로 39-1, 유정빌딩 2층 (중화동)', 206886.476566053, 455496.619419948, '서울특별시 중랑구 중화동 305-44 유정빌딩 ')
(180, '성지동물병원', '서울특별시 중랑구 면목로 311 (면목동)', 207683.608993998, 453071.827543665, '서울특별시 중랑구 면목동 634-5 ')
(181, '금란동물병원', '서울특별시 중랑구 용마산로 532, 금란동물병원 (망우동)', 208814.147876688, 455130.344037856, '서울특별시 중랑구 망우동 364-27 금란동물병원 ')
(182, '서울우유협동조합유우진료소', '서울특별시 중랑구 중랑천로 71 (상봉동)', 206321.919332707, 454381.762925507, '서울특별시 중랑구 상봉동 137-7 ')
(183, '주연동물병원', '서울특별시 중랑구 면목로 273 (면목동)', 207501.313934626, 452781.027328961, '서울특별시 중랑구 면목동 353-25 ')

In [19]:
con.commit()
con.close()

In [3]:
big='서울'
small = '영등포'
cursor.execute("SELECT * FROM hospital WHERE new_address LIKE ? AND new_address LIKE ?", (f"{big}%",f"%{small}%",))
rows = cursor.fetchall()
df = pd.DataFrame(rows, columns=["ids", "name", "new_address", "x_coor", "y_coor", "old_address"])

In [5]:
df.head()

,ids,name,new_address,x_coor,y_coor,old_address
0,582,24시여의동물의료센터,"서울특별시 영등포구 국회대로74길 4, KCTOWER 1층 (여의도동)",192914.020706,447594.120761,서울특별시 영등포구 여의도동 13-13 KCTOWER
1,583,서울 스템셀 동물병원,"서울특별시 영등포구 의사당대로 38, 101-105호 (여의도동)",192747.4193,447054.988337,서울특별시 영등포구 여의도동 17 여의도더샵아일랜드파크
2,584,포커스동물의료센터,"서울특별시 영등포구 신풍로 28, 제에코동 지하1층 제비128~131호 (신길동, ...",,,서울특별시 영등포구 신길동 4975 비스타동원 제에코동 제비128호
3,585,대방동물병원,"서울특별시 영등포구 신풍로25길 13, 그레이트 빌 1층 (신길동)",192854.52826,444333.005548,서울특별시 영등포구 신길동 583 그레이트 빌
4,586,신풍동물종합병원,서울특별시 영등포구 신길로 70 (신길동),191844.925515,444053.006857,서울특별시 영등포구 신길동 3611

In [9]:
import pandas as pd
from pyproj import Transformer

SOURCE_CRS = "EPSG:5174"
TARGET_CRS = "EPSG:4326"

transformer = Transformer.from_crs(
    SOURCE_CRS,
    TARGET_CRS,
    always_xy=True
)

# 빈 문자열 등을 NaN으로 변환
df["x_coor"] = pd.to_numeric(df["x_coor"], errors="coerce")
df["y_coor"] = pd.to_numeric(df["y_coor"], errors="coerce")

# 좌표가 모두 있는 행만 사용
valid_df = df.dropna(subset=["x_coor", "y_coor"])

# 결과는 longitude, latitude 순서
long, lat = transformer.transform(
    valid_df["x_coor"].to_numpy(),
    valid_df["y_coor"].to_numpy()
)

# 각각 리스트로 변환
lat_list = lat.tolist()
long_list = long.tolist()

print(lat_list)
print(long_list)

[37.53056351323466, 37.52570465924969, 37.5011805527265, 37.4986493394837, 37.51364670303015, 37.50720801748846, 37.52434256638593, 37.521885072350905, 37.53323409781005, 37.521474878572704, 37.51083558617471, 37.493469364326955, 37.51817233170882, 37.4984236969818, 37.518227007147956, 37.52155065566818, 37.513432400084454, 37.52856042300471, 37.518435542439946, 37.512152856646864, 37.51872325199329, 37.532091696948264, 37.5009076003841, 37.52233930271352, 37.52785310473224, 37.50492036789684, 37.524394184199146, 37.52065228688053, 37.51707545285829, 37.53681366487267, 37.50296343505899, 37.50578126870338, 37.50900750050661, 37.49440621247672, 37.51848348129383, 37.506696359747615, 37.52321327566502, 37.50392117061062, 37.50552617399449]
[126.92062114104046, 126.91874166829275, 126.91998004682236, 126.908565541678, 126.91984859606823, 126.91122934921798, 126.90424585111258, 126.88466373746196, 126.90226798188937, 126.93250349061645, 126.9120419394371, 126.90980685133499, 126.92605363733999, 126.89552022011486, 126.89592407301703, 126.89625372347524, 126.91853415710571, 126.90421315604733, 126.91319820595017, 126.91596374950045, 126.93355935564725, 126.90504031822974, 126.91356283815558, 126.89116891883549, 126.8984320443223, 126.90816634474731, 126.90675264887166, 126.88992217205795, 126.90334092163012, 126.89964500314306, 126.909607765004, 126.906320055557, 126.89661809948758, 126.90705997727952, 126.8893501444412, 126.90193310112447, 126.93308580427218, 126.9211168951113, 126.91148270916024]